// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package mongo

import (
	"log/slog"
	"strings"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollection sets the collection option.
func WithCollection[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.collection = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.collection = vv
		}
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithOperationsTimeout sets the operationsTimeout option.
func WithOperationsTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.operationsTimeout = v
	}
}

// WithRenewRatio sets the renewRatio option.
func WithRenewRatio(v float64) Option {
	return func(o *options) {
		o.renewRatio = v
	}
}

// WithTTL sets the ttl option.
func WithTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ttl = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		collection:        DefaultCollection,
		logger:            slog.New(slog.DiscardHandler),
		operationsTimeout: DefaultOperationsTimeout,
		renewRatio:        DefaultRenewRatio,
		ttl:               DefaultTTL,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
