// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package cache

import (
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/encoding/serializer"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithName sets the name option.
func WithName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.name = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.name = vv
		}
	}
}

// WithSerializer sets the serializer option.
func WithSerializer(v serializer.Serializer) Option {
	return func(o *options) {
		o.serializer = v
	}
}

// WithTtl sets the ttl option.
func WithTtl(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ttl = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		serializer: &serializer.JSON{},
		ttl:        DefaultTTL,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
