// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package errstatus

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCacheDisabled enables the cacheDisabled option.
func WithCacheDisabled() Option {
	return func(o *options) {
		o.cacheDisabled = true
	}
}

// WithCacheOnlySentinel enables the cacheOnlySentinel option.
func WithCacheOnlySentinel() Option {
	return func(o *options) {
		o.cacheOnlySentinel = true
	}
}

// WithCacheSize sets the cacheSize option.
func WithCacheSize(v int) Option {
	return func(o *options) {
		o.cacheSize = v
	}
}

// WithDomain sets the domain option.
func WithDomain[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.domain = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.domain = vv
		}
	}
}

// WithFinalizer sets the finalizer option.
func WithFinalizer(v Finalizer) Option {
	return func(o *options) {
		o.finalizer = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithSentinelErrors sets the sentinelErrors option.
func WithSentinelErrors(v ...error) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.sentinelErrors = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cacheSize: DefaultCacheSize,
		logger:    slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
