// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package negcache

// Option is a functional option for configuring options.
type Option func(o *options)

// WithMetrics sets the metrics option.
func WithMetrics(v *Metrics) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.metrics = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
