// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package secrets

import (
	"log/slog"

	"github.com/altessa-s/go-atlas/core/runtime/retry"
	"github.com/altessa-s/go-atlas/observability/health"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithExponentialConfig sets the exponentialConfig option.
func WithExponentialConfig(v retry.ExponentialConfig) Option {
	return func(o *options) {
		o.exponentialConfig = v
	}
}

// WithHealthCoordinator sets the healthCoordinator option.
func WithHealthCoordinator(v *health.Coordinator) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.healthCoordinator = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxRetries sets the maxRetries option.
func WithMaxRetries(v int) Option {
	return func(o *options) {
		o.maxRetries = v
	}
}

// WithNegativeFilter sets the negativeFilter option.
func WithNegativeFilter(v Filter) Option {
	return func(o *options) {
		o.negativeFilter = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.scheduler = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		exponentialConfig: defaultExponentialConfig(),
		logger:            slog.New(slog.DiscardHandler),
		maxRetries:        DefaultMaxRetries,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
