// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package rlimits

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDisableCoreDumps enables the disableCoreDumps option.
func WithDisableCoreDumps() Option {
	return func(o *options) {
		o.disableCoreDumps = true
	}
}

// WithMaxFileSizeBytes sets the maxFileSizeBytes option.
func WithMaxFileSizeBytes(v int64) Option {
	return func(o *options) {
		o.maxFileSizeBytes = v
	}
}

// WithMaxOpenFiles sets the maxOpenFiles option.
func WithMaxOpenFiles(v int64) Option {
	return func(o *options) {
		o.maxOpenFiles = v
	}
}

// WithMaxProcesses sets the maxProcesses option.
func WithMaxProcesses(v int64) Option {
	return func(o *options) {
		o.maxProcesses = v
	}
}

// WithMemoryBytes sets the memoryBytes option.
func WithMemoryBytes(v int64) Option {
	return func(o *options) {
		o.memoryBytes = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
