// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package prometheus

import (
	"github.com/prometheus/client_golang/prometheus"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithGatherer sets the gatherer option.
func WithGatherer(v prometheus.Gatherer) Option {
	return func(o *options) {
		o.gatherer = v
	}
}

// WithRegisterer sets the registerer option.
func WithRegisterer(v prometheus.Registerer) Option {
	return func(o *options) {
		o.registerer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
