// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package securityheaders

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/http/server/middlewares/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithContentSecurityPolicy sets the contentSecurityPolicy option.
func WithContentSecurityPolicy[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.contentSecurityPolicy = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.contentSecurityPolicy = vv
		}
	}
}

// WithContentTypeNoSniff enables the contentTypeNoSniff option.
func WithContentTypeNoSniff() Option {
	return func(o *options) {
		o.contentTypeNoSniff = true
	}
}

// WithFrameOptions sets the frameOptions option.
func WithFrameOptions(v FrameOptions) Option {
	return func(o *options) {
		o.frameOptions = v
	}
}

// WithHstsEnabled enables the hstsEnabled option.
func WithHstsEnabled() Option {
	return func(o *options) {
		o.hstsEnabled = true
	}
}

// WithHstsIncludeSubDomains enables the hstsIncludeSubDomains option.
func WithHstsIncludeSubDomains() Option {
	return func(o *options) {
		o.hstsIncludeSubDomains = true
	}
}

// WithHstsMaxAge sets the hstsMaxAge option.
func WithHstsMaxAge(v int) Option {
	return func(o *options) {
		o.hstsMaxAge = v
	}
}

// WithHstsPreload enables the hstsPreload option.
func WithHstsPreload() Option {
	return func(o *options) {
		o.hstsPreload = true
	}
}

// WithIgnorePaths sets the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithPermissionsPolicy sets the permissionsPolicy option.
func WithPermissionsPolicy[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.permissionsPolicy = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.permissionsPolicy = vv
		}
	}
}

// WithReferrerPolicy sets the referrerPolicy option.
func WithReferrerPolicy(v ReferrerPolicy) Option {
	return func(o *options) {
		o.referrerPolicy = v
	}
}

// WithXssProtectionDisabled enables the xssProtectionDisabled option.
func WithXssProtectionDisabled() Option {
	return func(o *options) {
		o.xssProtectionDisabled = true
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		contentTypeNoSniff:    true,
		frameOptions:          FrameOptionsDeny,
		hstsIncludeSubDomains: true,
		hstsMaxAge:            31536000,
		ignorePatterns:        defaults.IgnorePatterns,
		logger:                slog.New(slog.DiscardHandler),
		referrerPolicy:        ReferrerPolicyStrictOriginWhenCrossOrigin,
		xssProtectionDisabled: true,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
