// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package metrics

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
	"github.com/altessa-s/go-atlas/transport/http/server/middlewares/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithEnableSizeMetrics enables the enableSizeMetrics option.
func WithEnableSizeMetrics() Option {
	return func(o *options) {
		o.enableSizeMetrics = true
	}
}

// WithIgnorePaths sets the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMetricsSubsystem sets the metricsSubsystem option.
func WithMetricsSubsystem[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.metricsSubsystem = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.metricsSubsystem = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		ignorePatterns:   defaults.IgnorePatterns,
		logger:           slog.New(slog.DiscardHandler),
		metricsSubsystem: DefaultMetricsSubsystem,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
