// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package auth

import (
	"log/slog"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAuthTimeout sets the authTimeout option.
func WithAuthTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.authTimeout = v
	}
}

// WithBackoffBase sets the backoffBase option.
func WithBackoffBase(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.backoffBase = v
	}
}

// WithBackoffMax sets the backoffMax option.
func WithBackoffMax(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.backoffMax = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		authTimeout: DefaultAuthTimeout,
		backoffBase: DefaultBackoffBase,
		backoffMax:  DefaultBackoffMax,
		logger:      slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
