// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package console

import (
	"io"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithPrettyPrint enables the prettyPrint option.
func WithPrettyPrint() Option {
	return func(o *options) {
		o.prettyPrint = true
	}
}

// WithTimestamps enables the timestamps option.
func WithTimestamps() Option {
	return func(o *options) {
		o.timestamps = true
	}
}

// WithWriter sets the writer option.
func WithWriter(v io.Writer) Option {
	return func(o *options) {
		o.writer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		prettyPrint: DefaultPrettyPrint,
		timestamps:  DefaultTimestamps,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
