// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package mongodb

import (
	"strings"
)

// Option is a functional option for configuring a [Storage] instance created
// by [New]. Options are applied in order; later options override earlier ones.
type Option func(o *options)

// WithHistoryCollection overrides the MongoDB collection name used to store
// [scheduler.TaskHistory] documents. The default is [DefaultHistoryCollection].
// Empty strings and nil pointers are silently ignored, leaving the default
// unchanged.
func WithHistoryCollection[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.historyCollection = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.historyCollection = vv
		}
	}
}

// WithTasksCollection overrides the MongoDB collection name used to store
// [scheduler.TaskState] documents. The default is [DefaultTasksCollection].
// Empty strings and nil pointers are silently ignored, leaving the default
// unchanged.
func WithTasksCollection[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.tasksCollection = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.tasksCollection = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		historyCollection: DefaultHistoryCollection,
		tasksCollection:   DefaultTasksCollection,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
