// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package dlock

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/health"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithHealthCoordinator sets the healthCoordinator option.
func WithHealthCoordinator(v *health.Coordinator) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.healthCoordinator = v
	}
}

// WithHealthServiceName sets the healthServiceName option.
func WithHealthServiceName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.healthServiceName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.healthServiceName = vv
		}
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		healthServiceName: DefaultHealthServiceName,
		logger:            slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
