// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package dlock

import (
	"log/slog"
	"time"

	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.collector = v
	}
}

// WithLockAcquireTimeout sets the lockAcquireTimeout option.
func WithLockAcquireTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.lockAcquireTimeout = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		lockAcquireTimeout: DefaultLockAcquireTimeout,
		logger:             slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
