// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package jetstream

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/encoding/serializer"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAckWait sets the ackWait option.
func WithAckWait(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ackWait = v
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithConcurrency sets the concurrency option.
func WithConcurrency(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.concurrency = v
	}
}

// WithConsumer sets the consumer option.
func WithConsumer[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.consumer = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.consumer = vv
		}
	}
}

// WithDuplicateWindow sets the duplicateWindow option.
func WithDuplicateWindow(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.duplicateWindow = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxAge sets the maxAge option.
func WithMaxAge(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxAge = v
	}
}

// WithMaxDeliver sets the maxDeliver option.
func WithMaxDeliver(v int) Option {
	return func(o *options) {
		o.maxDeliver = v
	}
}

// WithRetryBaseDelay sets the retryBaseDelay option.
func WithRetryBaseDelay(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryBaseDelay = v
	}
}

// WithRetryMaxDelay sets the retryMaxDelay option.
func WithRetryMaxDelay(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryMaxDelay = v
	}
}

// WithSerializer sets the serializer option.
func WithSerializer(v serializer.Serializer) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.serializer = v
	}
}

// WithStream sets the stream option.
func WithStream[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.stream = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.stream = vv
		}
	}
}

// WithSubjectPrefix sets the subjectPrefix option.
func WithSubjectPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.subjectPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.subjectPrefix = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		ackWait:         DefaultAckWait,
		concurrency:     DefaultConcurrency,
		duplicateWindow: DefaultDuplicateWindow,
		logger:          slog.New(slog.DiscardHandler),
		maxDeliver:      DefaultMaxDeliver,
		retryBaseDelay:  DefaultRetryBaseDelay,
		retryMaxDelay:   DefaultRetryMaxDelay,
		serializer:      &serializer.JSON{},
		stream:          DefaultStream,
		subjectPrefix:   DefaultSubjectPrefix,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
