// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package serviceinfo

import (
	"strings"

	"github.com/altessa-s/go-atlas/core/runtime/appinfo"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithExtraMetadata sets the extraMetadata option.
func WithExtraMetadata(v map[string]string) Option {
	return func(o *options) {
		o.extraMetadata = v
	}
}

// WithLeaderProvider sets the leaderProvider option.
func WithLeaderProvider(v LeaderProvider) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.leaderProvider = v
	}
}

// WithServiceDescription sets the serviceDescription option.
func WithServiceDescription[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceDescription = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceDescription = vv
		}
	}
}

// WithServiceID sets the serviceID option.
func WithServiceID[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceID = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceID = vv
		}
	}
}

// WithServiceName sets the serviceName option.
func WithServiceName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceName = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		extraMetadata: make(map[string]string),
		serviceName:   appinfo.Name,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
