// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package client

import (
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/transport/http/client/limiters"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBreakerInterval sets the breakerInterval option.
func WithBreakerInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.breakerInterval = v
	}
}

// WithBreakerMaxRequests sets the breakerMaxRequests option.
func WithBreakerMaxRequests(v uint32) Option {
	return func(o *options) {
		o.breakerMaxRequests = v
	}
}

// WithBreakerName sets the breakerName option.
func WithBreakerName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.breakerName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.breakerName = vv
		}
	}
}

// WithBreakerTimeout sets the breakerTimeout option.
func WithBreakerTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.breakerTimeout = v
	}
}

// WithClient sets the client option.
func WithClient(v *http.Client) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.client = v
	}
}

// WithErrorHandler sets the errorHandler option.
func WithErrorHandler(v ErrorHandler) Option {
	return func(o *options) {
		o.errorHandler = v
	}
}

// WithLimiter sets the limiter option.
func WithLimiter(v limiters.RequestsLimiter) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.limiter = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxResponseSize sets the maxResponseSize option.
func WithMaxResponseSize(v int64) Option {
	return func(o *options) {
		o.maxResponseSize = v
	}
}

// WithRetryMax sets the retryMax option.
func WithRetryMax(v int) Option {
	return func(o *options) {
		o.retryMax = v
	}
}

// WithRetryPolicyHandler sets the retryPolicyHandler option.
func WithRetryPolicyHandler(v RetryPolicyHandler) Option {
	return func(o *options) {
		o.retryPolicyHandler = v
	}
}

// WithRetryWaitMax sets the retryWaitMax option.
func WithRetryWaitMax(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryWaitMax = v
	}
}

// WithRetryWaitMin sets the retryWaitMin option.
func WithRetryWaitMin(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryWaitMin = v
	}
}

// WithTransport sets the transport option.
func WithTransport(v *http.Transport) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.transport = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		breakerInterval:    DefaultBreakerInterval,
		breakerMaxRequests: DefaultBreakerMaxRequests,
		breakerTimeout:     DefaultBreakerTimeout,
		client:             defaultClient(),
		logger:             slog.New(slog.DiscardHandler),
		retryMax:           DefaultRetryMax,
		retryWaitMax:       DefaultRetryWaitMax,
		retryWaitMin:       DefaultRetryWaitMin,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
