// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package tlsvault

import (
	"log/slog"
	"net"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/security/tlsutils"

	vaultApi "github.com/hashicorp/vault/api"
)

// Option is a functional option for configuring options.
type Option func(o *options) error

// WithCacheDir sets the cacheDir option.
func WithCacheDir[T interface{ string | *string }](v T) Option {
	return func(o *options) error {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return nil
			}
			o.cacheDir = vv
		case *string:
			if t == nil {
				return nil
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return nil
			}
			o.cacheDir = vv
		}
		return nil
	}
}

// WithCommonName sets the commonName option.
func WithCommonName[T interface{ string | *string }](v T) Option {
	return func(o *options) error {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return nil
			}
			o.commonName = vv
		case *string:
			if t == nil {
				return nil
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return nil
			}
			o.commonName = vv
		}
		return nil
	}
}

// WithIpSubjectAlternativeNames sets the ipSubjectAlternativeNames option.
func WithIpSubjectAlternativeNames(v ...string) Option {
	return func(o *options) error {
		if len(v) == 0 {
			return nil
		}
		netIPs := make([]net.IP, 0, len(v))
		for _, s := range v {
			ip := net.ParseIP(s)
			if ip == nil {
				return ErrInvalidIP
			}
			netIPs = append(netIPs, ip)
		}

		o.ipSubjectAlternativeNames = netIPs
		return nil
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) error {
		if v == nil {
			return nil
		}
		o.logger = v
		return nil
	}
}

// WithOcspStapler sets the ocspStapler option.
func WithOcspStapler(v tlsutils.OCSPStapler) Option {
	return func(o *options) error {
		if v == nil {
			return nil
		}
		o.ocspStapler = v
		return nil
	}
}

// WithRenewBefore sets the renewBefore option.
func WithRenewBefore(v time.Duration) Option {
	return func(o *options) error {
		if v <= 0 {
			return nil
		}
		o.renewBefore = v
		return nil
	}
}

// WithRole sets the role option.
func WithRole[T interface{ string | *string }](v T) Option {
	return func(o *options) error {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return nil
			}
			o.role = vv
		case *string:
			if t == nil {
				return nil
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return nil
			}
			o.role = vv
		}
		return nil
	}
}

// WithSubjectAlternativeNames sets the subjectAlternativeNames option.
func WithSubjectAlternativeNames(v ...string) Option {
	return func(o *options) error {
		if len(v) == 0 {
			return nil
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.subjectAlternativeNames = transformed
		return nil
	}
}

// WithVc sets the vc option.
func WithVc(v *vaultApi.Client) Option {
	return func(o *options) error {
		if v == nil {
			return nil
		}
		o.vc = v
		return nil
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:      slog.New(slog.DiscardHandler),
		renewBefore: time.Minute * 10,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) (*options, error) {
	o := defaultOptions()
	for _, opt := range opts {
		if err := opt(o); err != nil {
			return nil, err
		}
	}
	return o, nil
}
