// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package cors

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/http/server/middlewares/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAllowAllOrigins enables the allowAllOrigins option.
func WithAllowAllOrigins() Option {
	return func(o *options) {
		o.allowAllOrigins = true
	}
}

// WithAllowCredentials enables the allowCredentials option.
func WithAllowCredentials() Option {
	return func(o *options) {
		o.allowCredentials = true
	}
}

// WithAllowPrivateNetwork enables the allowPrivateNetwork option.
func WithAllowPrivateNetwork() Option {
	return func(o *options) {
		o.allowPrivateNetwork = true
	}
}

// WithAllowedHeaders sets the allowedHeaders option.
func WithAllowedHeaders(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.allowedHeaders = transformed
	}
}

// WithAllowedMethods sets the allowedMethods option.
func WithAllowedMethods(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.allowedMethods = transformed
	}
}

// WithAllowedOriginPatterns sets the allowedOriginPatterns option.
func WithAllowedOriginPatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.allowedOriginPatterns = v
	}
}

// WithAllowedOrigins sets the allowedOrigins option.
func WithAllowedOrigins(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.allowedOrigins = transformed
	}
}

// WithExposedHeaders sets the exposedHeaders option.
func WithExposedHeaders(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.exposedHeaders = transformed
	}
}

// WithIgnorePaths sets the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxAge sets the maxAge option.
func WithMaxAge(v int) Option {
	return func(o *options) {
		o.maxAge = v
	}
}

// WithOptionsPassthrough enables the optionsPassthrough option.
func WithOptionsPassthrough() Option {
	return func(o *options) {
		o.optionsPassthrough = true
	}
}

// WithOptionsSuccessStatus sets the optionsSuccessStatus option.
func WithOptionsSuccessStatus(v int) Option {
	return func(o *options) {
		o.optionsSuccessStatus = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		allowedHeaders:       DefaultAllowedHeaders,
		allowedMethods:       DefaultAllowedMethods,
		exposedHeaders:       DefaultExposedHeaders,
		ignorePatterns:       defaults.IgnorePatterns,
		logger:               slog.New(slog.DiscardHandler),
		maxAge:               DefaultMaxAge,
		optionsSuccessStatus: 204,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
