// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package grpc

//go:generate go run github.com/altessa-s/go-atlas/cmd/optgen generate --type=options

import (
	"github.com/altessa-s/go-atlas/transport/internal/timeouts"

	"google.golang.org/grpc"

	baseserver "github.com/altessa-s/go-atlas/transport/internal/server"
)

// DefaultTimeoutConfig returns the default timeout configuration.
// These values provide reasonable defaults for most production deployments
// while allowing customization for specific requirements.
func DefaultTimeoutConfig() timeouts.Config {
	return timeouts.Default()
}

// options holds the merged configuration for [Server], combining base server
// settings (address, TLS, logger, timeouts) with gRPC-specific settings
// (server options, reflection). The gRPC-specific fields are code-generated
// by optgen; baseOpts is composed manually via [WithBaseOptions].
type options struct {
	// baseOpts holds base server options (no opt tag - managed manually)
	baseOpts []baseserver.Option

	// gRPC-specific options (generated by optgen)
	grpcOpts   []grpc.ServerOption `opt:"GrpcOptions"`
	reflection bool                `opt:"Reflection" optgen:"default=false"`
}

// WithBaseOptions adds base server options (TLS, listener, logger, address, name, timeouts).
// This is a convenience function to avoid duplicating wrapper functions for each base server option.
//
// Example:
//
//	srv, _ := grpc.New(
//	    grpc.WithBaseOptions(
//	        server.WithAddress(":50051"),
//	        server.WithLogger(slog.Default()),
//	        server.WithTLSConfig(tlsConfig),
//	    ),
//	    grpc.WithReflection(true),
//	)
func WithBaseOptions(opts ...baseserver.Option) Option {
	return func(c *options) {
		c.baseOpts = append(c.baseOpts, opts...)
	}
}
