// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package grpc

import (
	"google.golang.org/grpc"

	baseserver "github.com/altessa-s/go-atlas/transport/internal/server"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBaseOpts sets the baseOpts option.
func WithBaseOpts(v ...baseserver.Option) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.baseOpts = v
	}
}

// WithGrpcOptions sets the grpcOpts option.
func WithGrpcOptions(v ...grpc.ServerOption) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.grpcOpts = v
	}
}

// WithReflection enables the reflection option.
func WithReflection() Option {
	return func(o *options) {
		o.reflection = true
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		reflection: false,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
