// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/core/runtime/appinfo"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAppName sets the appName option.
func WithAppName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.appName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.appName = vv
		}
	}
}

// WithAppVersion sets the appVersion option.
func WithAppVersion[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.appVersion = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.appVersion = vv
		}
	}
}

// WithEnableMasking enables the enableMasking option.
func WithEnableMasking() Option {
	return func(o *options) {
		o.enableMasking = true
	}
}

// WithLevelVar sets the levelVar option.
func WithLevelVar(v *slog.LevelVar) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.levelVar = v
	}
}

// WithPrefixColors sets the prefixColors option.
func WithPrefixColors(v map[string][]int) Option {
	return func(o *options) {
		o.prefixColors = v
	}
}

// WithPrefixKey sets the prefixKey option.
func WithPrefixKey[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.prefixKey = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.prefixKey = vv
		}
	}
}

// WithServiceId sets the serviceId option.
func WithServiceId[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceId = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceId = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		appName:      appinfo.Name,
		appVersion:   appinfo.Version,
		prefixColors: map[string][]int{ModuleKey: {46}},
		prefixKey:    ModuleKey,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
