// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package concurrency

// Option is a functional option for configuring options.
type Option[T any] func(o *options[T])

// WithConcurrency sets the concurrency option.
func WithConcurrency[T any](v int) Option[T] {
	return func(o *options[T]) {
		o.concurrency = v
	}
}

// WithLimitFunc sets the limitFunc option.
func WithLimitFunc[T any](v ConcurrencyLimitFunc) Option[T] {
	return func(o *options[T]) {
		o.limitFunc = v
	}
}

// WithOnError sets the onError option.
func WithOnError[T any](v ErrorCallback[T]) Option[T] {
	return func(o *options[T]) {
		o.onError = v
	}
}

// WithOnSuccess sets the onSuccess option.
func WithOnSuccess[T any](v SuccessCallback[T]) Option[T] {
	return func(o *options[T]) {
		o.onSuccess = v
	}
}

// WithStopOnError enables the stopOnError option.
func WithStopOnError[T any]() Option[T] {
	return func(o *options[T]) {
		o.stopOnError = true
	}
}

// defaultOptions returns the default values for options.
func defaultOptions[T any]() *options[T] {
	return &options[T]{}
}

// newOptions creates a new options with the given options.
func newOptions[T any](opts ...Option[T]) *options[T] {
	o := defaultOptions[T]()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
