// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package proxydial

import (
	"crypto/tls"
	"net"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDialer sets the dialer option.
func WithDialer(v *net.Dialer) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.dialer = v
	}
}

// WithProxyTLSConfig sets the proxyTLSConfig option.
func WithProxyTLSConfig(v *tls.Config) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.proxyTLSConfig = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		dialer: DefaultDialer(),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
