// Copyright 2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package mongo

//go:generate go run github.com/altessa-s/go-atlas/cmd/optgen generate

// DefaultBSONTagName is the default struct tag key read to resolve a field's
// document name and modifiers (omitempty, omitonupdate). Override with
// [WithBsonTagName].
const DefaultBSONTagName = "bson"

// options carries translator configuration. Tunables are generated by optgen —
// never construct this struct directly; use the With* options.
//
// The translators own only the bson tag; field-behavior concerns (tag name,
// depth, strip kinds) belong to the behavior engine and are configured there via
// [github.com/altessa-s/go-atlas/domain/behavior.WithTagName] /
// [github.com/altessa-s/go-atlas/domain/behavior.WithMaxDepth] /
// [github.com/altessa-s/go-atlas/domain/behavior.WithKinds].
type options struct {
	bsonTagName string `optgen:"default=DefaultBSONTagName"`
}
