// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package broker

import (
	"log/slog"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithOutbox sets the outbox option.
func WithOutbox(v Outboxer) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.outbox = v
	}
}

// WithPublishConverter sets the publishConverter option.
func WithPublishConverter(v PublishConverter) Option {
	return func(o *options) {
		o.publishConverter = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
