// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=clientOptions

package idempotency

import (
	"strings"
)

// Option is a functional option for configuring clientOptions.
type ClientOption func(o *clientOptions)

// WithClientIdempotencyKeyHeader sets the idempotencyKeyHeader option.
func WithClientIdempotencyKeyHeader[T interface{ string | *string }](v T) ClientOption {
	return func(o *clientOptions) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyHeader = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyHeader = vv
		}
	}
}

// WithClientMethodFilter sets the methodFilter option.
func WithClientMethodFilter(v MethodFilter) ClientOption {
	return func(o *clientOptions) {
		o.methodFilter = v
	}
}

// WithClientSeedExtractor sets the seedExtractor option.
func WithClientSeedExtractor(v SeedExtractor) ClientOption {
	return func(o *clientOptions) {
		o.seedExtractor = v
	}
}

// defaultClientOptions returns the default values for clientOptions.
func defaultClientOptions() *clientOptions {
	return &clientOptions{
		idempotencyKeyHeader: DefaultIdempotencyKeyHeader,
		methodFilter:         DefaultClientMethodFilter,
		seedExtractor:        DefaultClientSeedExtractor,
	}
}

// newClientOptions creates a new clientOptions with the given options.
func newClientOptions(opts ...ClientOption) *clientOptions {
	o := defaultClientOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
