// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package idempotency

import (
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/grpc/interceptors/defaults"
	"github.com/altessa-s/go-atlas/transport/internal/fallback"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithEnforceMandatory sets the enforceMandatory option.
func WithEnforceMandatory(v bool) Option {
	return func(o *options) {
		o.enforceMandatory = v
	}
}

// WithEntityIDExtractor sets the entityIdExtractor option.
func WithEntityIDExtractor(v EntityIdExtractor) Option {
	return func(o *options) {
		o.entityIdExtractor = v
	}
}

// WithExposeEntityID enables the exposeEntityID option.
func WithExposeEntityID() Option {
	return func(o *options) {
		o.exposeEntityID = true
	}
}

// WithFallbackBehavior sets the fallbackBehavior option.
func WithFallbackBehavior(v fallback.Behavior) Option {
	return func(o *options) {
		o.fallbackBehavior = v
	}
}

// WithIdempotencyKeyEntityIDMetadata sets the idempotencyKeyEntityIdMetadata option.
func WithIdempotencyKeyEntityIDMetadata[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyEntityIdMetadata = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyEntityIdMetadata = vv
		}
	}
}

// WithIdempotencyKeyHeader sets the idempotencyKeyHeader option.
func WithIdempotencyKeyHeader[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyHeader = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyHeader = vv
		}
	}
}

// WithIdempotencyKeyStatusMetadata sets the idempotencyKeyStatusMetadata option.
func WithIdempotencyKeyStatusMetadata[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyStatusMetadata = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyStatusMetadata = vv
		}
	}
}

// WithIgnoreMethods sets the ignoreMethods option.
func WithIgnoreMethods(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignoreMethods = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithKeyFormatValidator sets the keyFormatValidator option.
func WithKeyFormatValidator(v KeyFormatValidator) Option {
	return func(o *options) {
		o.keyFormatValidator = v
	}
}

// WithStatusCreator sets the statusCreator option.
func WithStatusCreator(v StatusCreator) Option {
	return func(o *options) {
		o.statusCreator = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		enforceMandatory:               false,
		exposeEntityID:                 false,
		fallbackBehavior:               fallback.Deny,
		idempotencyKeyEntityIdMetadata: DefaultIdempotencyKeyEntityIdMetadata,
		idempotencyKeyHeader:           DefaultIdempotencyKeyHeader,
		idempotencyKeyStatusMetadata:   DefaultIdempotencyKeyStatusMetadata,
		ignorePatterns:                 defaults.IgnorePatterns,
		keyFormatValidator:             DefaultKeyValidator,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
