// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package logger

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/core/time/timeformat"
	"github.com/altessa-s/go-atlas/transport/http/server/middlewares/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBodyRedactor sets the bodyRedactor option.
func WithBodyRedactor(v BodyRedactFunc) Option {
	return func(o *options) {
		o.bodyRedactor = v
	}
}

// WithContextLogger sets the contextLogger option.
func WithContextLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.contextLogger = v
	}
}

// WithIgnoreMethods sets the ignoreMethods option.
func WithIgnoreMethods(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignoreMethods = transformed
	}
}

// WithIgnorePaths sets the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithIgnoreResponseCodes sets the ignoreResponseCodes option.
func WithIgnoreResponseCodes(v ...int) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignoreResponseCodes = v
	}
}

// WithLogRequest enables the logRequest option.
func WithLogRequest() Option {
	return func(o *options) {
		o.logRequest = true
	}
}

// WithLogResponse enables the logResponse option.
func WithLogResponse() Option {
	return func(o *options) {
		o.logResponse = true
	}
}

// WithLogResponseCodes sets the logResponseCodes option.
func WithLogResponseCodes(v ...int) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.logResponseCodes = v
	}
}

// WithTimeFormat sets the timeFormat option.
func WithTimeFormat(v timeformat.Format) Option {
	return func(o *options) {
		o.timeFormat = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		bodyRedactor:   nil,
		contextLogger:  nil,
		ignorePatterns: defaults.IgnorePatterns,
		timeFormat:     timeformat.RFC3339,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
