// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package endpointfilter

import (
	"regexp"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCacheSize sets the cacheSize option.
func WithCacheSize(v int) Option {
	return func(o *options) {
		o.cacheSize = v
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cacheSize: DefaultIgnoreCacheSize,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
