// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"
	"strings"

	"github.com/nats-io/nats.go"

	"github.com/altessa-s/go-atlas/core/runtime/appinfo"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithKey sets the key option.
func WithKey[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.key = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.key = vv
		}
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithNatsConn sets the natsConn option.
func WithNatsConn(v *nats.Conn) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.natsConn = v
	}
}

// WithNodeId sets the nodeId option.
func WithNodeId[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.nodeId = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.nodeId = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		key:    appinfo.Name,
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
