// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package saga

import (
	"context"
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/encoding/serializer"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithContext sets the baseCtx option.
func WithContext(v context.Context) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.baseCtx = v
	}
}

// WithLeaderElector sets the leaderElector option.
func WithLeaderElector(v LeaderElector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.leaderElector = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxCompensationAttempts sets the maxCompensationAttempts option.
func WithMaxCompensationAttempts(v int) Option {
	return func(o *options) {
		o.maxCompensationAttempts = v
	}
}

// WithMaxStepAttempts sets the maxStepAttempts option.
func WithMaxStepAttempts(v int) Option {
	return func(o *options) {
		o.maxStepAttempts = v
	}
}

// WithRecoveryBatchSize sets the recoveryBatchSize option.
func WithRecoveryBatchSize(v int) Option {
	return func(o *options) {
		o.recoveryBatchSize = v
	}
}

// WithRecoverySchedule sets the recoverySchedule option.
func WithRecoverySchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.recoverySchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.recoverySchedule = vv
		}
	}
}

// WithRecoveryTaskID sets the recoveryTaskID option.
func WithRecoveryTaskID[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.recoveryTaskID = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.recoveryTaskID = vv
		}
	}
}

// WithSagaTimeout sets the sagaTimeout option.
func WithSagaTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.sagaTimeout = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.scheduler = v
	}
}

// WithSerializer sets the serializer option.
func WithSerializer(v serializer.Serializer) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.serializer = v
	}
}

// WithStepConcurrency sets the stepConcurrency option.
func WithStepConcurrency(v int) Option {
	return func(o *options) {
		o.stepConcurrency = v
	}
}

// WithStepRetryBaseDelay sets the stepRetryBaseDelay option.
func WithStepRetryBaseDelay(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.stepRetryBaseDelay = v
	}
}

// WithStepRetryMaxDelay sets the stepRetryMaxDelay option.
func WithStepRetryMaxDelay(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.stepRetryMaxDelay = v
	}
}

// WithStepTimeout sets the stepTimeout option.
func WithStepTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.stepTimeout = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:                  slog.New(slog.DiscardHandler),
		maxCompensationAttempts: DefaultMaxCompensationAttempts,
		maxStepAttempts:         DefaultMaxStepAttempts,
		recoveryBatchSize:       DefaultRecoveryBatchSize,
		recoverySchedule:        DefaultRecoverySchedule,
		recoveryTaskID:          DefaultRecoveryTaskID,
		serializer:              &serializer.JSON{},
		stepRetryBaseDelay:      DefaultStepRetryBaseDelay,
		stepRetryMaxDelay:       DefaultStepRetryMaxDelay,
		stepTimeout:             DefaultStepTimeout,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
