// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package leadelect

import (
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithHandlerTimeout sets the handlerTimeout option.
func WithHandlerTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.handlerTimeout = v
	}
}

// WithTTL sets the ttl option.
func WithTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ttl = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		handlerTimeout: DefaultHandlerTimeout,
		ttl:            DefaultTTL,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
