// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package server

import (
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"

	baseserver "github.com/altessa-s/go-atlas/transport/internal/server"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBaseOptions sets the baseOpts option.
func WithBaseOptions(v ...baseserver.Option) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.baseOpts = v
	}
}

// WithIdleTimeout sets the idleTimeout option.
func WithIdleTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.idleTimeout = v
	}
}

// WithMaxHeaderBytes sets the maxHeaderBytes option.
func WithMaxHeaderBytes(v int) Option {
	return func(o *options) {
		o.maxHeaderBytes = v
	}
}

// WithReadTimeout sets the readTimeout option.
func WithReadTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.readTimeout = v
	}
}

// WithRouter sets the router option.
func WithRouter(v Router) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.router = v
	}
}

// WithWriteTimeout sets the writeTimeout option.
func WithWriteTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.writeTimeout = v
	}
}

// WithWriter sets the writer option.
func WithWriter(v ResponseWriter) Option {
	return func(o *options) {
		o.writer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		idleTimeout:    DefaultIdleTimeout,
		maxHeaderBytes: DefaultMaxHeaderBytes,
		readTimeout:    DefaultReadTimeout,
		writeTimeout:   DefaultWriteTimeout,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
