// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package tracing

import (
	"strings"

	"github.com/altessa-s/go-atlas/core/runtime/appinfo"
	"github.com/altessa-s/go-atlas/observability/tracing/adapters"
	"github.com/altessa-s/go-atlas/observability/tracing/sampler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAdapter sets the adapter option.
func WithAdapter(v adapters.Adapter) Option {
	return func(o *options) {
		o.adapter = v
	}
}

// WithEnvironment sets the environment option.
func WithEnvironment[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.environment = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.environment = vv
		}
	}
}

// WithSampler sets the sampler option.
func WithSampler(v sampler.Sampler) Option {
	return func(o *options) {
		o.sampler = v
	}
}

// WithServiceName sets the serviceName option.
func WithServiceName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceName = vv
		}
	}
}

// WithServiceVersion sets the serviceVersion option.
func WithServiceVersion[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceVersion = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceVersion = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		environment:    appinfo.EnvLabel(),
		serviceName:    appinfo.Name,
		serviceVersion: appinfo.Version,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
