// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package memory

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCapacity sets the capacity option.
func WithCapacity(v uint) Option {
	return func(o *options) {
		o.capacity = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		capacity: DefaultCapacity,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
