// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=defaultBuilderOptions

package writer

// Option is a functional option for configuring defaultBuilderOptions.
type DefaultBuilderOption func(o *defaultBuilderOptions)

// WithDefaultBuilderErrorConverter sets the errorConverter option.
func WithDefaultBuilderErrorConverter(v ErrorConverter) DefaultBuilderOption {
	return func(o *defaultBuilderOptions) {
		o.errorConverter = v
	}
}

// defaultDefaultBuilderOptions returns the default values for defaultBuilderOptions.
func defaultDefaultBuilderOptions() *defaultBuilderOptions {
	return &defaultBuilderOptions{}
}

// newDefaultBuilderOptions creates a new defaultBuilderOptions with the given options.
func newDefaultBuilderOptions(opts ...DefaultBuilderOption) *defaultBuilderOptions {
	o := defaultDefaultBuilderOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
