// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package writer

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/transport/http/server/codec"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDefaultCodec sets the defaultCodec option.
func WithDefaultCodec[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.defaultCodec = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.defaultCodec = vv
		}
	}
}

// WithErrorConverter sets the errorConverter option.
func WithErrorConverter(v ErrorConverter) Option {
	return func(o *options) {
		o.errorConverter = v
	}
}

// WithFallbackOnNegotiationError enables the fallbackOnNegotiationError option.
func WithFallbackOnNegotiationError() Option {
	return func(o *options) {
		o.fallbackOnNegotiationError = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxBodySize sets the maxBodySize option.
func WithMaxBodySize(v int64) Option {
	return func(o *options) {
		o.maxBodySize = v
	}
}

// WithRegistry sets the registry option.
func WithRegistry(v *codec.Registry) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.registry = v
	}
}

// WithResponseBuilder sets the responseBuilder option.
func WithResponseBuilder(v Builder) Option {
	return func(o *options) {
		o.responseBuilder = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		defaultCodec:               DefaultCodecJSON,
		fallbackOnNegotiationError: true,
		logger:                     slog.New(slog.DiscardHandler),
		registry:                   codec.DefaultRegistry(),
		responseBuilder:            NewDefault(),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
