// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package lru

// Option is a functional option for configuring options.
type Option func(o *options)

// WithShardCount sets the shardCount option.
func WithShardCount(v int) Option {
	return func(o *options) {
		o.shardCount = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
