// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package tokenbucket

import (
	"log/slog"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithClientService sets the clientService option.
func WithClientService(v ClientService) Option {
	return func(o *options) {
		o.clientService = v
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithExtractClientIPAddress sets the extractClientIPAddress option.
func WithExtractClientIPAddress(v ExtractIPFunc) Option {
	return func(o *options) {
		o.extractClientIPAddress = v
	}
}

// WithExtractToken sets the extractToken option.
func WithExtractToken(v ExtractTokenFunc) Option {
	return func(o *options) {
		o.extractToken = v
	}
}

// WithIPCacheSize sets the iPCacheSize option.
func WithIPCacheSize(v int) Option {
	return func(o *options) {
		o.iPCacheSize = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		extractClientIPAddress: defaultExtractClientIp,
		extractToken:           defaultExtractAuthToken,
		iPCacheSize:            DefaultCacheSize,
		logger:                 slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
