// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package vault

import (
	"strings"

	"github.com/altessa-s/go-atlas/core/runtime/concurrency"
	"github.com/altessa-s/go-atlas/security/secrets"
	"github.com/altessa-s/go-atlas/security/secrets/codec"
	"github.com/altessa-s/go-atlas/security/secrets/codec/keys/base64"
	"github.com/altessa-s/go-atlas/security/secrets/codec/values/json"
)

// Option is a functional option for configuring options.
type Option[T any] func(o *options[T])

// WithCas enables the cas option.
func WithCas[T any]() Option[T] {
	return func(o *options[T]) {
		o.cas = true
	}
}

// WithConcurrencyLimitFunc sets the concurrencyLimitFunc option.
func WithConcurrencyLimitFunc[T any](v concurrency.ConcurrencyLimitFunc) Option[T] {
	return func(o *options[T]) {
		if v == nil {
			return
		}
		o.concurrencyLimitFunc = v
	}
}

// WithKeyDecoder sets the keyDecoder option.
func WithKeyDecoder[T any](v codec.KeyDecoder) Option[T] {
	return func(o *options[T]) {
		if v == nil {
			return
		}
		o.keyDecoder = v
	}
}

// WithLocker sets the locker option.
func WithLocker[T any](v secrets.Locker) Option[T] {
	return func(o *options[T]) {
		if v == nil {
			return
		}
		o.locker = v
	}
}

// WithMountPath sets the mountPath option.
func WithMountPath[T any](v string) Option[T] {
	return func(o *options[T]) {
		o.mountPath = strings.TrimPrefix(strings.TrimSpace(v), "/")
	}
}

// WithSecretPath sets the secretPath option.
func WithSecretPath[T any](v string) Option[T] {
	return func(o *options[T]) {
		o.secretPath = strings.TrimPrefix(strings.TrimSpace(v), "/")
	}
}

// WithValueDecoder sets the valueDecoder option.
func WithValueDecoder[T any](v codec.ValueDecoder[T]) Option[T] {
	return func(o *options[T]) {
		if v == nil {
			return
		}
		o.valueDecoder = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions[T any]() *options[T] {
	return &options[T]{
		keyDecoder:   base64.NewKeyDecoder(),
		mountPath:    DefaultMountPath,
		secretPath:   DefaultSecretPath,
		valueDecoder: json.NewValueDecoder[T](),
	}
}

// newOptions creates a new options with the given options.
func newOptions[T any](opts ...Option[T]) *options[T] {
	o := defaultOptions[T]()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
