// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"

	"github.com/nats-io/nats.go/jetstream"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
	redis "github.com/redis/go-redis/v9"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithJetstream sets the jetstream option.
func WithJetstream(v jetstream.JetStream) Option {
	return func(o *options) {
		o.jetstream = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithRedisClient sets the redisClient option.
func WithRedisClient(v redis.UniversalClient) Option {
	return func(o *options) {
		o.redisClient = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.scheduler = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
