// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package tlss3

import (
	"context"
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/security/tlsutils"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithContext sets the ctx option.
func WithContext(v context.Context) Option {
	return func(o *options) {
		o.ctx = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithOcspStapler sets the ocspStapler option.
func WithOcspStapler(v tlsutils.OCSPStapler) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.ocspStapler = v
	}
}

// WithPollInterval sets the pollInterval option.
func WithPollInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.pollInterval = v
	}
}

// WithReloadNotifyChan sets the reloadNotifyChan option.
func WithReloadNotifyChan(v chan struct{}) Option {
	return func(o *options) {
		o.reloadNotifyChan = v
	}
}

// WithS3Client sets the s3Client option.
func WithS3Client(v S3API) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.s3Client = v
	}
}

// WithSseCustomerKey sets the sseCustomerKey option.
func WithSseCustomerKey[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.sseCustomerKey = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.sseCustomerKey = vv
		}
	}
}

// WithSseCustomerKeyMD5 sets the sseCustomerKeyMD5 option.
func WithSseCustomerKeyMD5[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.sseCustomerKeyMD5 = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.sseCustomerKeyMD5 = vv
		}
	}
}

// WithSseType sets the sseType option.
func WithSseType(v SSEType) Option {
	return func(o *options) {
		o.sseType = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
