// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package grpc

import (
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithActorExtractor sets the actorExtractor option.
func WithActorExtractor(v ActorExtractor) Option {
	return func(o *options) {
		o.actorExtractor = v
	}
}

// WithIgnoreMethods sets the ignoreMethods option.
func WithIgnoreMethods(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignoreMethods = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithRequestIDExtractor sets the requestIDExtractor option.
func WithRequestIDExtractor(v RequestIDExtractor) Option {
	return func(o *options) {
		o.requestIDExtractor = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
