// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package requestid

import (
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithGenerateIfMissing enables the generateIfMissing option.
func WithGenerateIfMissing() Option {
	return func(o *options) {
		o.generateIfMissing = true
	}
}

// WithHeaderName sets the headerName option.
func WithHeaderName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.headerName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.headerName = vv
		}
	}
}

// WithUUIDGenerator sets the uuidGenerator option.
func WithUUIDGenerator(v UUIDGenerator) Option {
	return func(o *options) {
		o.uuidGenerator = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		generateIfMissing: true,
		headerName:        DefaultHTTPHeaderName,
		uuidGenerator:     defaultUUIDGenerator,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
