// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"

	"go.mongodb.org/mongo-driver/v2/mongo"

	"github.com/altessa-s/go-atlas/data/leadelect"

	redis "github.com/redis/go-redis/v9"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithLeaderElector sets the leaderElector option.
func WithLeaderElector(v leadelect.LeaderElector) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.leaderElector = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMongoDb sets the mongoDb option.
func WithMongoDb(v *mongo.Database) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.mongoDb = v
	}
}

// WithRedisClient sets the redisClient option.
func WithRedisClient(v redis.UniversalClient) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.redisClient = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
