// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"

	"go.mongodb.org/mongo-driver/v2/mongo"

	"github.com/altessa-s/go-atlas/data/leadelect"

	redis "github.com/redis/go-redis/v9"
)

// Option is a functional option for configuring a [Factory]. Pass Option values
// to [New] to control which infrastructure clients and behavioral settings the
// Factory carries.
type Option func(o *options)

// WithLeaderElector sets the [leadelect.LeaderElector] used by schedulers
// created through this Factory. When set, the leader elector is automatically
// passed to every [scheduler.Scheduler] so that only the elected leader
// instance executes tasks. A nil value is silently ignored, leaving the
// default (no leader election) in place.
func WithLeaderElector(v leadelect.LeaderElector) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.leaderElector = v
	}
}

// WithLogger sets the structured logger used by the [Factory] and forwarded
// to every [scheduler.Scheduler] it creates. A nil value is silently ignored;
// in that case a no-op discard logger is used by default.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMongoDb sets the [mongo.Database] used when creating MongoDB-backed
// storage via [Factory.CreateStorageFromConfig] or
// [Factory.CreateMongoStorageFromConfig]. A nil value is silently ignored.
// The database must be provided before requesting MongoDB storage; otherwise
// the Factory returns an error at creation time.
func WithMongoDb(v *mongo.Database) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.mongoDb = v
	}
}

// WithRedisClient sets the [redis.UniversalClient] used when creating
// Redis-backed storage via [Factory.CreateStorageFromConfig] or
// [Factory.CreateRedisStorageFromConfig]. A nil value is silently ignored.
// The client must be provided before requesting Redis storage; otherwise the
// Factory returns an error at creation time.
func WithRedisClient(v redis.UniversalClient) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.redisClient = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
