// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package recovery

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithHealthCheckSchedule sets the healthCheckSchedule option.
func WithHealthCheckSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.healthCheckSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.healthCheckSchedule = vv
		}
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxRecoveryAttempts sets the maxRecoveryAttempts option.
func WithMaxRecoveryAttempts(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxRecoveryAttempts = v
	}
}

// WithRecoveryBackoff sets the recoveryBackoff option.
func WithRecoveryBackoff(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.recoveryBackoff = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.scheduler = v
	}
}

// WithStaleRecoveryCleanupSchedule sets the staleRecoveryCleanupSchedule option.
func WithStaleRecoveryCleanupSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.staleRecoveryCleanupSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.staleRecoveryCleanupSchedule = vv
		}
	}
}

// WithStaleRecoveryTimeout sets the staleRecoveryTimeout option.
func WithStaleRecoveryTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.staleRecoveryTimeout = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:               slog.New(slog.DiscardHandler),
		maxRecoveryAttempts:  DefaultMaxRecoveryAttempts,
		recoveryBackoff:      DefaultRecoveryBackoff,
		staleRecoveryTimeout: DefaultStaleRecoveryTimeout,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
