// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package nats

import (
	"strings"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBucket sets the bucket option.
func WithBucket[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.bucket = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.bucket = vv
		}
	}
}

// WithBucketTTL sets the bucketTTL option.
func WithBucketTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.bucketTTL = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		bucket:    DefaultBucket,
		bucketTTL: DefaultBucketTTL,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
