// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package tlsfile

import (
	"context"
	"log/slog"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/security/tlsutils"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithContext sets the ctx option.
func WithContext(v context.Context) Option {
	return func(o *options) {
		o.ctx = v
	}
}

// WithEnableWatcher enables the enableWatcher option.
func WithEnableWatcher() Option {
	return func(o *options) {
		o.enableWatcher = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithOcspStapler sets the ocspStapler option.
func WithOcspStapler(v tlsutils.OCSPStapler) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.ocspStapler = v
	}
}

// WithReloadNotifyChan sets the reloadNotifyChan option.
func WithReloadNotifyChan(v chan struct{}) Option {
	return func(o *options) {
		o.reloadNotifyChan = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
