// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package masking

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCaseSensitive enables the caseSensitive option.
func WithCaseSensitive() Option {
	return func(o *options) {
		o.caseSensitive = true
	}
}

// WithDefaultMask sets the defaultMask option.
func WithDefaultMask(v MaskFunc) Option {
	return func(o *options) {
		o.defaultMask = v
	}
}

// WithMaskNestedFields enables the maskNestedFields option.
func WithMaskNestedFields() Option {
	return func(o *options) {
		o.maskNestedFields = true
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		fields: make(map[string]MaskFunc),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
