// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package fieldmask

//go:generate stringer -type=Kind -linecomment -output=kind_string.go

import "strings"

// Kind selects which fieldmask operation the interceptor applies to a gRPC
// method. The String method is generated by stringer; line-comments below
// carry the lowercase tokens used in logs.
type Kind uint8

const (
	// KindNone leaves the request and response untouched. Used as the
	// default for non-AIP methods and as the result of the empty
	// classification.
	KindNone Kind = iota // none

	// KindUpdate runs [fieldmask.FieldMask.ApplyUpdateMask] against the
	// request's update_mask and sibling resource sub-message before the
	// handler executes. Default classification for methods whose short
	// name starts with "Update", "Patch", or "BatchUpdate".
	KindUpdate // update

	// KindRead runs [fieldmask.FieldMask.Filter] against the response
	// using the request's read_mask after the handler returns. Default
	// classification for methods whose short name starts with "Get",
	// "List", "Search", or "BatchGet".
	KindRead // read

	// KindSkip disables both the update-mask and read-mask passes for
	// this method. Useful for opting a specific method out of the
	// interceptor entirely without removing it from the chain.
	KindSkip // skip
)

// ClassifyMethod returns the default Kind for a fully-qualified gRPC method
// name (the value passed by grpc-go as info.FullMethod, e.g.
// "/x.v1.X/UpdateBucket"). The classification looks at the short name only —
// the part after the final "/". Empty input returns KindNone.
//
// The prefix match is case-sensitive: "updateBucket" does not match.
func ClassifyMethod(fullMethod string) Kind {
	short := shortMethod(fullMethod)
	if short == "" {
		return KindNone
	}

	switch {
	case strings.HasPrefix(short, "BatchUpdate"):
		return KindUpdate
	case strings.HasPrefix(short, "BatchGet"):
		return KindRead
	case strings.HasPrefix(short, "Update"), strings.HasPrefix(short, "Patch"):
		return KindUpdate
	case strings.HasPrefix(short, "Get"),
		strings.HasPrefix(short, "List"),
		strings.HasPrefix(short, "Search"):
		return KindRead
	}

	return KindNone
}

// shortMethod returns the part of fullMethod after the final slash, or the
// whole string when no slash is present.
func shortMethod(fullMethod string) string {
	if i := strings.LastIndexByte(fullMethod, '/'); i >= 0 {
		return fullMethod[i+1:]
	}

	return fullMethod
}
