// Code generated by "stringer -type=Kind -linecomment -output=kind_string.go"; DO NOT EDIT.

package fieldmask

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindNone-0]
	_ = x[KindUpdate-1]
	_ = x[KindRead-2]
	_ = x[KindSkip-3]
}

const _Kind_name = "noneupdatereadskip"

var _Kind_index = [...]uint8{0, 4, 10, 14, 18}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
