// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package fieldmask

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/grpc/interceptors/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithIgnoreMethods sets the ignoreMethods option.
func WithIgnoreMethods(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignoreMethods = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaskFieldName sets the maskFieldName option.
func WithMaskFieldName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.maskFieldName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.maskFieldName = vv
		}
	}
}

// WithResourceFieldName sets the resourceFieldName option.
func WithResourceFieldName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.resourceFieldName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.resourceFieldName = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		ignorePatterns: defaults.IgnorePatterns,
		logger:         slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
