// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package uniq

import (
	"github.com/altessa-s/go-atlas/core/encoding/serializer"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithSerializer sets the serializer option.
func WithSerializer(v serializer.Serializer) Option {
	return func(o *options) {
		o.serializer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		serializer: &serializer.JSON{},
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
