// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package jwt

import (
	"io"
	"strings"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithClock sets the clock option.
func WithClock(v Clock) Option {
	return func(o *options) {
		o.clock = v
	}
}

// WithExpectedTokenType sets the expectedTokenType option.
func WithExpectedTokenType[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.expectedTokenType = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.expectedTokenType = vv
		}
	}
}

// WithExpirationRequired enables the expirationRequired option.
func WithExpirationRequired() Option {
	return func(o *options) {
		o.expirationRequired = true
	}
}

// WithIssuedAt enables the issuedAt option.
func WithIssuedAt() Option {
	return func(o *options) {
		o.issuedAt = true
	}
}

// WithIssuer sets the issuer option.
func WithIssuer[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.issuer = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.issuer = vv
		}
	}
}

// WithLeeway sets the leeway option.
func WithLeeway(v time.Duration) Option {
	return func(o *options) {
		if v < 0 {
			return
		}
		o.leeway = v
	}
}

// WithMaxTokenLifetime sets the maxTokenLifetime option.
func WithMaxTokenLifetime(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxTokenLifetime = v
	}
}

// WithNotBeforeRequired enables the notBeforeRequired option.
func WithNotBeforeRequired() Option {
	return func(o *options) {
		o.notBeforeRequired = true
	}
}

// WithRand sets the rand option.
func WithRand(v io.Reader) Option {
	return func(o *options) {
		o.rand = v
	}
}

// WithSubject sets the subject option.
func WithSubject[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.subject = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.subject = vv
		}
	}
}

// WithTokenType sets the tokenType option.
func WithTokenType[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.tokenType = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.tokenType = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		allowedAlgorithms:  DefaultAllowedAlgorithms(),
		clock:              defaultClock,
		expirationRequired: DefaultExpirationRequired,
		issuer:             DefaultIssuer,
		leeway:             DefaultLeeway,
		maxTokenLifetime:   DefaultMaxTokenLifetime,
		rand:               defaultRand,
		tokenType:          DefaultTokenType,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
