// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=parserOptions

package orderby

import (
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring parserOptions.
type ParserOption func(o *parserOptions)

// WithAllowArrayIndexPaths enables the allowArrayIndices option.
func WithAllowArrayIndexPaths() ParserOption {
	return func(o *parserOptions) {
		o.allowArrayIndices = true
	}
}

// WithCaseSensitiveDirection enables the caseSensitiveDirection option.
func WithCaseSensitiveDirection() ParserOption {
	return func(o *parserOptions) {
		o.caseSensitiveDirection = true
	}
}

// WithMaxExpressionLength sets the maxExpressionLength option.
func WithMaxExpressionLength(v int) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.maxExpressionLength = v
	}
}

// WithMaxFieldNameLength sets the maxFieldNameLength option.
func WithMaxFieldNameLength(v int) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.maxFieldNameLength = v
	}
}

// WithMaxFieldPathDepth sets the maxFieldPathDepth option.
func WithMaxFieldPathDepth(v int) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.maxFieldPathDepth = v
	}
}

// WithMaxKeys sets the maxKeys option.
func WithMaxKeys(v int) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.maxKeys = v
	}
}

// WithParserCacheSize sets the cacheSize option.
func WithParserCacheSize(v int) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.cacheSize = v
	}
}

// WithParserCollector sets the collector option.
func WithParserCollector(v metrics.Collector) ParserOption {
	return func(o *parserOptions) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithParserNoCache enables the noCache option.
func WithParserNoCache() ParserOption {
	return func(o *parserOptions) {
		o.noCache = true
	}
}

// defaultParserOptions returns the default values for parserOptions.
func defaultParserOptions() *parserOptions {
	return &parserOptions{
		maxExpressionLength: DefaultMaxExpressionLength,
		maxFieldNameLength:  DefaultMaxFieldNameLength,
		maxFieldPathDepth:   DefaultMaxFieldPathDepth,
		maxKeys:             DefaultMaxKeys,
		cacheSize:           DefaultParserCacheSize,
	}
}

// newParserOptions creates a new parserOptions with the given options.
func newParserOptions(opts ...ParserOption) *parserOptions {
	o := defaultParserOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
