// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=translatorOptions

package orderby

// Option is a functional option for configuring translatorOptions.
type TranslatorOption func(o *translatorOptions)

// WithUntrustedInput enables the untrustedInput option.
func WithUntrustedInput() TranslatorOption {
	return func(o *translatorOptions) {
		o.untrustedInput = true
	}
}

// defaultTranslatorOptions returns the default values for translatorOptions.
func defaultTranslatorOptions() *translatorOptions {
	return &translatorOptions{}
}

// newTranslatorOptions creates a new translatorOptions with the given options.
func newTranslatorOptions(opts ...TranslatorOption) *translatorOptions {
	o := defaultTranslatorOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
