// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package plugins

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDir sets the dir option.
func WithDir[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.dir = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.dir = vv
		}
	}
}

// WithDisabled appends to the disabled option.
func WithDisabled(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.disabled = append(o.disabled, transformed...)
	}
}

// WithHostVersion sets the hostVersion option.
func WithHostVersion[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.hostVersion = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.hostVersion = vv
		}
	}
}

// WithHostVersionMode sets the hostVersionMode option.
func WithHostVersionMode(v HostVersionMode) Option {
	return func(o *options) {
		o.hostVersionMode = v
	}
}

// WithInitTimeout sets the initTimeout option.
func WithInitTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.initTimeout = v
	}
}

// WithLoad appends to the load option.
func WithLoad(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.load = append(o.load, transformed...)
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMetrics sets the metrics option.
func WithMetrics(v metrics.Collector) Option {
	return func(o *options) {
		o.metrics = v
	}
}

// WithWatchDebounce sets the watchDebounce option.
func WithWatchDebounce(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.watchDebounce = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		dir:             DefaultDir,
		hostVersionMode: DefaultHostVersionMode,
		initTimeout:     DefaultInitTimeout,
		logger:          slog.New(slog.DiscardHandler),
		watchDebounce:   DefaultWatchDebounce,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
