// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package plugins

//go:generate go run github.com/altessa-s/go-atlas/cmd/optgen generate

import (
	"crypto"
	"fmt"
	"log/slog"
	"slices"
	"time"

	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Default values for plugin manager options.
const (
	DefaultDir           = "./plugins"
	DefaultInitTimeout   = 5 * time.Second
	DefaultWatchDebounce = 200 * time.Millisecond
	// DefaultSignatureMode is the default signature verification mode.
	// Set to SignatureRequire for security by default.
	DefaultSignatureMode = SignatureRequire
)

// HostVersionMode controls strictness of the host major version check
// performed when both [Descriptor.HostVersion] and [WithHostVersion]
// declare a version. The default is [HostVersionEnforce] — production
// deployments should keep this default; the other modes exist for
// canary rollouts and emergency operations.
type HostVersionMode int

const (
	// HostVersionEnforce returns [ErrHostVersionMismatch] and quarantines
	// the plugin when its declared major does not match the host's.
	// This is the default and matches the behavior most operators want.
	HostVersionEnforce HostVersionMode = iota

	// HostVersionWarn logs a warning on mismatch but allows the plugin
	// to load. Intended for canary phases where operators want visibility
	// before enforcing.
	HostVersionWarn

	// HostVersionDisabled skips the check entirely, even when both sides
	// declare a version. Use as a temporary kill-switch when an urgent
	// rollout requires loading a plugin that declares an incompatible
	// major; pair with a follow-up plugin rebuild.
	HostVersionDisabled
)

// DefaultHostVersionMode is the default value applied via optgen.
const DefaultHostVersionMode = HostVersionEnforce

// options contains Manager configuration.
type options struct {
	logger          *slog.Logger
	dir             string            `optgen:"default=DefaultDir"`
	load            []string          `optgen:"append"`
	disabled        []string          `optgen:"append"`
	initTimeout     time.Duration     `optgen:"default=DefaultInitTimeout"`
	watchDebounce   time.Duration     `optgen:"default=DefaultWatchDebounce"`
	hostVersion     string            // host service semver, compared against Descriptor.HostVersion at load time
	hostVersionMode HostVersionMode   `optgen:"default=DefaultHostVersionMode"`
	sandbox         SandboxOptions    `optgen:"manual"`
	signature       signatureState    `opt:"-"` // resolved key + mode; set by WithSignature
	signatureErr    error             `opt:"-"` // deferred PEM parse error from WithSignature
	metrics         metrics.Collector // metrics collector for observability
}

// WithSandbox configures Linux process-hardening primitives applied lazily on
// the first [Manager.Load]. See [SandboxOptions] for the threat model and the
// host-wide cost of every primitive.
//
// WithSandbox clones every slice field inside o ([LandlockOptions.ReadPaths],
// [LandlockOptions.ReadWritePaths], [CapabilitiesOptions.Keep]) so that
// later mutations to the caller's slices cannot reach the manager. This
// matters because operator config is often built incrementally and a
// stale slice header would otherwise let a "Validate then build" sequence
// be subverted by a post-Validate slice append.
//
// Manual option (not generated by optgen) because [SandboxOptions] is a
// struct, not a primitive.
func WithSandbox(o SandboxOptions) Option {
	return func(opts *options) {
		o.Landlock.ReadPaths = slices.Clone(o.Landlock.ReadPaths)
		o.Landlock.ReadWritePaths = slices.Clone(o.Landlock.ReadWritePaths)
		o.Capabilities.Keep = slices.Clone(o.Capabilities.Keep)
		opts.sandbox = o
	}
}

// WithSignature configures plugin signature verification. The public
// key is resolved eagerly: PEM parsing and key-type validation happen
// at option-apply time. Since [NewManager] does not return an error,
// parse failures are deferred to the first [Manager.Load] call.
//
// Manual option (not generated by optgen) because [SignatureOptions]
// contains a [crypto.PublicKey] interface.
func WithSignature(o SignatureOptions) Option {
	return func(opts *options) {
		key, err := loadPublicKey(o)
		if err != nil {
			opts.signatureErr = err
			return
		}
		opts.signature = signatureState{
			mode:   o.Mode,
			pubKey: key,
		}
	}
}

// WithMultiKeySignature configures signature verification with multiple public
// keys for key rotation support. During a key rotation period, both the old
// and new keys can verify plugins, allowing for gradual rollout.
//
// Example:
//
//	mgr := plugins.NewManager(
//	    plugins.WithMultiKeySignature(plugins.MultiKeySignatureOptions{
//	        Mode: plugins.SignatureRequire,
//	        PublicKeyPaths: []string{
//	            "/etc/keys/new-public.pem",  // Try new key first
//	            "/etc/keys/old-public.pem",  // Fall back to old key
//	        },
//	    }),
//	)
func WithMultiKeySignature(opts MultiKeySignatureOptions) Option {
	return func(o *options) {
		// Load all keys
		var keys []crypto.PublicKey
		var loadErr error

		if len(opts.PublicKeys) > 0 {
			keys = opts.PublicKeys
		} else if len(opts.PublicKeyPaths) > 0 {
			keys, loadErr = loadMultiplePublicKeys(opts)
		}

		if loadErr != nil {
			o.signatureErr = loadErr
			return
		}

		if len(keys) == 0 && opts.Mode != SignatureDisabled {
			o.signatureErr = fmt.Errorf("%w: no public keys configured", ErrSignatureConfig)
			return
		}

		// Store as multi-key state
		o.signature = signatureState{
			mode:    opts.Mode,
			pubKeys: keys,
		}
	}
}

// WithSignatureDisabled disables signature verification.
// SECURITY WARNING: This completely disables signature verification,
// allowing unsigned plugins to be loaded. Use only in development or tests.
// For production, use WithSignature with a proper public key.
func WithSignatureDisabled() Option {
	return func(opts *options) {
		opts.signature = signatureState{
			mode: SignatureDisabled,
		}
	}
}
