// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package redis

import (
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithExpectedItems sets the expectedItems option.
func WithExpectedItems(v int64) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.expectedItems = v
	}
}

// WithFalsePositiveRate sets the falsePositiveRate option.
func WithFalsePositiveRate(v float64) Option {
	return func(o *options) {
		if v < 0 {
			return
		}
		o.falsePositiveRate = v
	}
}

// WithKeyPrefix sets the keyPrefix option.
func WithKeyPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.keyPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.keyPrefix = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		expectedItems:     DefaultExpectedItems,
		falsePositiveRate: DefaultFalsePositiveRate,
		keyPrefix:         DefaultKeyPrefix,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
