// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package server

import (
	"crypto/tls"
	"log/slog"
	"net"
	"strings"

	"github.com/altessa-s/go-atlas/transport/internal/timeouts"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAddress sets the address option.
func WithAddress[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.ToLower(strings.TrimSpace(t))
			if vv == "" {
				return
			}
			o.address = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.ToLower(strings.TrimSpace(*t))
			if vv == "" {
				return
			}
			o.address = vv
		}
	}
}

// WithListener sets the listener option.
func WithListener(v net.Listener) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.listener = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithName sets the name option.
func WithName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.ToLower(strings.TrimSpace(t))
			if vv == "" {
				return
			}
			o.name = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.ToLower(strings.TrimSpace(*t))
			if vv == "" {
				return
			}
			o.name = vv
		}
	}
}

// WithTimeouts sets the timeouts option.
func WithTimeouts(v timeouts.Config) Option {
	return func(o *options) {
		o.timeouts = v
	}
}

// WithTlsConfig sets the tlsConfig option.
func WithTlsConfig(v *tls.Config) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.tlsConfig = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		address:  DefaultAddress,
		logger:   slog.New(slog.DiscardHandler),
		name:     DefaultName,
		timeouts: timeouts.Default(),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
