// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package gitlab

import (
	"log/slog"
	"strings"

	httpclient "github.com/altessa-s/go-atlas/transport/http/client"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDir sets the dir option.
func WithDir[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.dir = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.dir = vv
		}
	}
}

// WithEndpoint sets the endpoint option.
func WithEndpoint[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.endpoint = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.endpoint = vv
		}
	}
}

// WithHTTPClientOptions appends to the httpClientOptions option.
func WithHTTPClientOptions(v ...httpclient.Option) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.httpClientOptions = append(o.httpClientOptions, v...)
	}
}

// WithIncludeData enables the includeData option.
func WithIncludeData() Option {
	return func(o *options) {
		o.includeData = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithProjectID sets the projectID option.
func WithProjectID(v int) Option {
	return func(o *options) {
		o.projectID = v
	}
}

// WithRef sets the ref option.
func WithRef[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.ref = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.ref = vv
		}
	}
}

// WithToken sets the token option.
func WithToken[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.token = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.token = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
		ref:    "main",
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
