// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package gitlab

import (
	"log/slog"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDir sets the dir option.
func WithDir(v string) Option {
	return func(o *options) {
		o.dir = v
	}
}

// WithEndpoint sets the endpoint option.
func WithEndpoint(v string) Option {
	return func(o *options) {
		o.endpoint = v
	}
}

// WithIncludeData enables the includeData option.
func WithIncludeData() Option {
	return func(o *options) {
		o.includeData = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithProjectID sets the projectID option.
func WithProjectID(v int) Option {
	return func(o *options) {
		o.projectID = v
	}
}

// WithRef sets the ref option.
func WithRef(v string) Option {
	return func(o *options) {
		o.ref = v
	}
}

// WithRetryMax sets the retryMax option.
func WithRetryMax(v int) Option {
	return func(o *options) {
		o.retryMax = v
	}
}

// WithRetryWaitMax sets the retryWaitMax option.
func WithRetryWaitMax(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryWaitMax = v
	}
}

// WithRetryWaitMin sets the retryWaitMin option.
func WithRetryWaitMin(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryWaitMin = v
	}
}

// WithToken sets the token option.
func WithToken(v string) Option {
	return func(o *options) {
		o.token = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
		ref:    "main",
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
