// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package opa

import (
	"log/slog"
	"time"

	"github.com/altessa-s/go-atlas/observability/health"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDecisionLogging enables the decisionLogging option.
func WithDecisionLogging() Option {
	return func(o *options) {
		o.decisionLogging = true
	}
}

// WithHealthCoordinator sets the healthCoordinator option.
func WithHealthCoordinator(v *health.Coordinator) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.healthCoordinator = v
	}
}

// WithPollInterval sets the pollInterval option.
func WithPollInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.pollInterval = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.scheduler = v
	}
}

// WithWatchChannelSize sets the watchChannelSize option.
func WithWatchChannelSize(v int) Option {
	return func(o *options) {
		o.watchChannelSize = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:           slog.New(slog.DiscardHandler),
		watchChannelSize: DefaultWatchBufferSize,
		pollInterval:     DefaultPollInterval,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
