// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package fieldbehavior

//go:generate stringer -type=Kind -linecomment -output=kind_string.go

import "strings"

// Kind selects which fieldbehavior Strip* function the interceptor applies to
// the request payload of a gRPC method. The String method is generated by
// stringer; line-comments below carry the lowercase tokens used in logs.
type Kind uint8

const (
	// KindNone leaves the request payload untouched. Used for Get/List/Delete
	// and other read- or action-style methods.
	KindNone Kind = iota // none

	// KindCreate runs fieldbehavior.StripCreate on the request payload.
	// Default classification for methods whose short name starts with
	// "Create" or "BatchCreate".
	KindCreate // create

	// KindUpdate runs fieldbehavior.StripUpdate on the request payload.
	// Default classification for methods whose short name starts with
	// "Update", "Patch", or "BatchUpdate".
	KindUpdate // update

	// KindSkip disables both request and response stripping for the method.
	// Useful for methods whose payloads are known not to contain any
	// field_behavior-annotated fields, or for opting a specific method out of
	// the global response strip.
	KindSkip // skip
)

// ClassifyMethod returns the default Kind for a fully-qualified gRPC method
// name (the value passed by grpc-go as info.FullMethod, e.g.
// "/x.v1.X/CreateBucket"). The classification looks at the short name only —
// the part after the final "/". Empty input returns KindNone.
//
// The prefix match is case-sensitive: "Createbucket" does not match.
func ClassifyMethod(fullMethod string) Kind {
	short := shortMethod(fullMethod)
	if short == "" {
		return KindNone
	}

	switch {
	case strings.HasPrefix(short, "BatchCreate"):
		return KindCreate
	case strings.HasPrefix(short, "BatchUpdate"):
		return KindUpdate
	case strings.HasPrefix(short, "Create"):
		return KindCreate
	case strings.HasPrefix(short, "Update"), strings.HasPrefix(short, "Patch"):
		return KindUpdate
	}

	return KindNone
}

// shortMethod returns the part of fullMethod after the final slash, or the
// whole string when no slash is present.
func shortMethod(fullMethod string) string {
	if i := strings.LastIndexByte(fullMethod, '/'); i >= 0 {
		return fullMethod[i+1:]
	}

	return fullMethod
}
