// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package clientip

import (
	"log/slog"
	"net/netip"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCacheDisabled enables the cacheDisabled option.
func WithCacheDisabled() Option {
	return func(o *options) {
		o.cacheDisabled = true
	}
}

// WithCacheSize sets the cacheSize option.
func WithCacheSize(v int) Option {
	return func(o *options) {
		o.cacheSize = v
	}
}

// WithHeaders sets the headers option.
func WithHeaders(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.headers = transformed
	}
}

// WithHeadersEnabled enables the headersEnabled option.
func WithHeadersEnabled() Option {
	return func(o *options) {
		o.headersEnabled = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithTrustedPeers sets the trustedPeers option.
func WithTrustedPeers(v ...netip.Prefix) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.trustedPeers = v
	}
}

// WithTrustedProxies sets the trustedProxies option.
func WithTrustedProxies(v ...netip.Prefix) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.trustedProxies = v
	}
}

// WithTrustedProxiesCount sets the trustedProxiesCount option.
func WithTrustedProxiesCount(v uint) Option {
	return func(o *options) {
		o.trustedProxiesCount = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cacheDisabled:       DefaultCacheDisabled,
		cacheSize:           DefaultCacheSize,
		headers:             DefaultHeaders(),
		headersEnabled:      DefaultHeadersEnabled,
		logger:              slog.New(slog.DiscardHandler),
		trustedProxiesCount: DefaultTrustedProxiesCount,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
