// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package idempotency

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/http/server/middlewares/defaults"
	"github.com/altessa-s/go-atlas/transport/internal/fallback"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithEnforceMandatory sets the enforceMandatory option.
func WithEnforceMandatory(v bool) Option {
	return func(o *options) {
		o.enforceMandatory = v
	}
}

// WithEntityIdExtractor sets the entityIdExtractor option.
func WithEntityIdExtractor(v EntityIdExtractor) Option {
	return func(o *options) {
		o.entityIdExtractor = v
	}
}

// WithErrorHandler sets the errorHandler option.
func WithErrorHandler(v ErrorHandler) Option {
	return func(o *options) {
		o.errorHandler = v
	}
}

// WithFallbackBehavior sets the fallbackBehavior option.
func WithFallbackBehavior(v fallback.Behavior) Option {
	return func(o *options) {
		o.fallbackBehavior = v
	}
}

// WithIdempotencyKeyEntityIdHeader sets the idempotencyKeyEntityIdHeader option.
func WithIdempotencyKeyEntityIdHeader[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyEntityIdHeader = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyEntityIdHeader = vv
		}
	}
}

// WithIdempotencyKeyHeader sets the idempotencyKeyHeader option.
func WithIdempotencyKeyHeader[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyHeader = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyHeader = vv
		}
	}
}

// WithIdempotencyKeyStatusHeader sets the idempotencyKeyStatusHeader option.
func WithIdempotencyKeyStatusHeader[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.idempotencyKeyStatusHeader = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.idempotencyKeyStatusHeader = vv
		}
	}
}

// WithIgnorePaths sets the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithKeyFormatValidator sets the keyFormatValidator option.
func WithKeyFormatValidator(v KeyFormatValidator) Option {
	return func(o *options) {
		o.keyFormatValidator = v
	}
}

// WithKeyLogMode sets the keyLogMode option.
func WithKeyLogMode(v KeyLogMode) Option {
	return func(o *options) {
		o.keyLogMode = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		enforceMandatory:             false,
		fallbackBehavior:             fallback.Deny,
		idempotencyKeyEntityIdHeader: DefaultIdempotencyKeyEntityIdHeader,
		idempotencyKeyHeader:         DefaultIdempotencyKeyHeader,
		idempotencyKeyStatusHeader:   DefaultIdempotencyKeyStatusHeader,
		ignorePatterns:               defaults.IgnorePatterns,
		keyFormatValidator:           DefaultKeyValidator,
		keyLogMode:                   DefaultKeyLogMode,
		logger:                       slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
