// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package prefixed

import (
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithPrefix sets the prefix option.
func WithPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.prefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.prefix = vv
		}
	}
}

// WithPrefixFormatter sets the prefixFormatter option.
func WithPrefixFormatter(v Formatter) Option {
	return func(o *options) {
		o.prefixFormatter = v
	}
}

// WithPrefixSeparator sets the prefixSeparator option.
func WithPrefixSeparator[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.prefixSeparator = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.prefixSeparator = vv
		}
	}
}

// WithPrefixesDelimiter sets the prefixesDelimiter option.
func WithPrefixesDelimiter[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.prefixesDelimiter = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.prefixesDelimiter = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		prefixFormatter:   DefaultFormatter,
		prefixSeparator:   DefaultPrefixSeparator,
		prefixesDelimiter: DefaultPrefixesDelimiter,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
