// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package pool

import (
	"log/slog"
	"time"

	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCleanupInterval sets the cleanupInterval option.
func WithCleanupInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.cleanupInterval = v
	}
}

// WithClientFactory sets the clientFactory option.
func WithClientFactory(v ClientFactory) Option {
	return func(o *options) {
		o.clientFactory = v
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.collector = v
	}
}

// WithConnectTimeout sets the connectTimeout option.
func WithConnectTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.connectTimeout = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxIdleTime sets the maxIdleTime option.
func WithMaxIdleTime(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxIdleTime = v
	}
}

// WithSize sets the size option.
func WithSize(v int) Option {
	return func(o *options) {
		o.size = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cleanupInterval: DefaultCleanupInterval,
		connectTimeout:  DefaultConnectTimeout,
		logger:          slog.New(slog.DiscardHandler),
		maxIdleTime:     DefaultMaxIdleTime,
		size:            DefaultPoolSize,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
