// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package selfjwt

import (
	"io"
	"strings"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCacheMaxEntries sets the cacheMaxEntries option.
func WithCacheMaxEntries(v int) Option {
	return func(o *options) {
		o.cacheMaxEntries = v
	}
}

// WithCacheTTL sets the cacheTTL option.
func WithCacheTTL(v time.Duration) Option {
	return func(o *options) {
		if v < 0 {
			return
		}
		o.cacheTTL = v
	}
}

// WithClock sets the clock option.
func WithClock(v Clock) Option {
	return func(o *options) {
		o.clock = v
	}
}

// WithClockSkew sets the clockSkew option.
func WithClockSkew(v time.Duration) Option {
	return func(o *options) {
		if v < 0 {
			return
		}
		o.clockSkew = v
	}
}

// WithIssuer sets the issuer option.
func WithIssuer[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.issuer = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.issuer = vv
		}
	}
}

// WithMaxTokenLifetime sets the maxTokenLifetime option.
func WithMaxTokenLifetime(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxTokenLifetime = v
	}
}

// WithMetrics sets the metrics option.
func WithMetrics(v *Metrics) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.metrics = v
	}
}

// WithRand sets the rand option.
func WithRand(v io.Reader) Option {
	return func(o *options) {
		o.rand = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		allowedAlgorithms: defaultAllowedAlgorithms,
		cacheMaxEntries:   DefaultCacheMaxEntries,
		cacheTTL:          DefaultCacheTTL,
		clock:             defaultClock,
		clockSkew:         DefaultClockSkew,
		issuer:            DefaultIssuer,
		maxTokenLifetime:  DefaultMaxTokenLifetime,
		rand:              defaultRand,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
