// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package filesystem

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithChecksums sets the checksums option.
func WithChecksums(v map[string]string) Option {
	return func(o *options) {
		o.checksums = v
	}
}

// WithExtensions sets the extensions option.
func WithExtensions(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.extensions = transformed
	}
}

// WithIncludeData enables the includeData option.
func WithIncludeData() Option {
	return func(o *options) {
		o.includeData = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		checksums:  nil,
		extensions: DefaultExtensions,
		logger:     slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
