// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package hmacsign

import (
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithClock sets the clock option.
func WithClock(v Clock) Option {
	return func(o *options) {
		o.clock = v
	}
}

// WithTolerance sets the tolerance option.
func WithTolerance(v time.Duration) Option {
	return func(o *options) {
		if v < 0 {
			return
		}
		o.tolerance = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		clock:     defaultClock,
		tolerance: DefaultTolerance,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
