// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package outbox

import (
	"context"
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCleanupSchedule sets the cleanupSchedule option.
func WithCleanupSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.cleanupSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.cleanupSchedule = vv
		}
	}
}

// WithCleanupTaskID sets the cleanupTaskID option.
func WithCleanupTaskID[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.cleanupTaskID = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.cleanupTaskID = vv
		}
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithContext sets the baseCtx option.
func WithContext(v context.Context) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.baseCtx = v
	}
}

// WithDispatchSchedule sets the dispatchSchedule option.
func WithDispatchSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.dispatchSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.dispatchSchedule = vv
		}
	}
}

// WithDispatchTaskID sets the dispatchTaskID option.
func WithDispatchTaskID[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.dispatchTaskID = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.dispatchTaskID = vv
		}
	}
}

// WithEventsBatchSize sets the eventsBatchSize option.
func WithEventsBatchSize(v uint32) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.eventsBatchSize = v
	}
}

// WithExpireSchedule sets the expireSchedule option.
func WithExpireSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.expireSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.expireSchedule = vv
		}
	}
}

// WithExpireTaskID sets the expireTaskID option.
func WithExpireTaskID[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.expireTaskID = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.expireTaskID = vv
		}
	}
}

// WithFetchTimeout sets the fetchTimeout option.
func WithFetchTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.fetchTimeout = v
	}
}

// WithHandleTimeout sets the handleTimeout option.
func WithHandleTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.handleTimeout = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithRetryMaxAttempts sets the retryMaxAttempts option.
func WithRetryMaxAttempts(v uint32) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryMaxAttempts = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.scheduler = v
	}
}

// WithUnlockSchedule sets the unlockSchedule option.
func WithUnlockSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.unlockSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.unlockSchedule = vv
		}
	}
}

// WithUnlockTaskID sets the unlockTaskID option.
func WithUnlockTaskID[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.unlockTaskID = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.unlockTaskID = vv
		}
	}
}

// WithUpdateTimeout sets the updateTimeout option.
func WithUpdateTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.updateTimeout = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cleanupTaskID:           DefaultCleanupTaskID,
		dispatchTaskID:          DefaultDispatchTaskID,
		eventsBatchSize:         DefaultEventsBatchSize,
		expireTaskID:            DefaultExpireTaskID,
		fetchTimeout:            DefaultFetchTimeout,
		handleTimeout:           DefaultHandleTimeout,
		logger:                  slog.New(slog.DiscardHandler),
		publishedEventsLifetime: DefaultPublishedEventsLifetime,
		retryMaxAttempts:        DefaultRetryMaxAttempts,
		unlockTaskID:            DefaultUnlockTaskID,
		updateTimeout:           DefaultUpdateTimeout,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
