// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package retry

import (
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithMaxElapsedTime sets the maxElapsedTime option.
func WithMaxElapsedTime(v time.Duration) Option {
	return func(o *options) {
		o.maxElapsedTime = v
	}
}

// WithNextDelay sets the nextDelay option.
func WithNextDelay(v NextDelayFunc) Option {
	return func(o *options) {
		o.nextDelay = v
	}
}

// WithOnRetry sets the onRetry option.
func WithOnRetry(v OnRetryFunc) Option {
	return func(o *options) {
		o.onRetry = v
	}
}

// WithShouldRetry sets the shouldRetry option.
func WithShouldRetry(v ShouldRetryFunc) Option {
	return func(o *options) {
		o.shouldRetry = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
