// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=config

package mongo

import (
	"log/slog"
	"strings"

	"go.mongodb.org/mongo-driver/v2/mongo"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/data/mongo/kms"
	"github.com/altessa-s/go-atlas/observability/metrics"

	mongoOptions "go.mongodb.org/mongo-driver/v2/mongo/options"
)

// Option is a functional option for configuring config.
type Option func(o *config)

// WithBSONTagName sets the BSONTagName option.
func WithBSONTagName[T interface{ string | *string }](v T) Option {
	return func(o *config) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.BSONTagName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.BSONTagName = vv
		}
	}
}

// WithClient sets the Client option.
func WithClient(v *mongo.Client) Option {
	return func(o *config) {
		if v == nil {
			return
		}
		o.Client = v
	}
}

// WithClientOptions sets the ClientOptions option.
func WithClientOptions(v *mongoOptions.ClientOptions) Option {
	return func(o *config) {
		if v == nil {
			return
		}
		o.ClientOptions = v
	}
}

// WithCollector sets the Collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *config) {
		if nilcheck.IsNil(v) {
			return
		}
		o.Collector = v
	}
}

// WithEncryptionEnabled enables the EncryptionEnabled option.
func WithEncryptionEnabled() Option {
	return func(o *config) {
		o.EncryptionEnabled = true
	}
}

// WithEncryptionTagName sets the EncryptionTagName option.
func WithEncryptionTagName[T interface{ string | *string }](v T) Option {
	return func(o *config) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.EncryptionTagName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.EncryptionTagName = vv
		}
	}
}

// WithKMS sets the KMS option.
func WithKMS(v kms.Provider) Option {
	return func(o *config) {
		o.KMS = v
	}
}

// WithLogger sets the Logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *config) {
		if v == nil {
			return
		}
		o.Logger = v
	}
}

// WithVaultCollection sets the VaultCollection option.
func WithVaultCollection[T interface{ string | *string }](v T) Option {
	return func(o *config) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.VaultCollection = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.VaultCollection = vv
		}
	}
}

// WithVaultDatabase sets the VaultDatabase option.
func WithVaultDatabase[T interface{ string | *string }](v T) Option {
	return func(o *config) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.VaultDatabase = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.VaultDatabase = vv
		}
	}
}

// defaultConfig returns the default values for config.
func defaultConfig() *config {
	return &config{
		BSONTagName:        DefaultBSONTagName,
		EncryptionTagName:  DefaultEncryptionTagName,
		Logger:             slog.New(slog.DiscardHandler),
		TransactionOptions: DefaultTransactionOptions(),
		VaultCollection:    DefaultVaultCollection,
	}
}

// newConfig creates a new config with the given options.
func newConfig(opts ...Option) *config {
	o := defaultConfig()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
