// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=parserOptions

package mongo

import (
	"reflect"
	"strings"
	"time"
)

// Option is a functional option for configuring parserOptions.
type ParserOption func(o *parserOptions)

// WithParserBSONTagName sets the bsonTagName option.
func WithParserBSONTagName[T interface{ string | *string }](v T) ParserOption {
	return func(o *parserOptions) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.bsonTagName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.bsonTagName = vv
		}
	}
}

// WithParserCacheEvictionAge sets the cacheEvictionAge option.
func WithParserCacheEvictionAge(v time.Duration) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.cacheEvictionAge = v
	}
}

// WithParserCacheSize sets the cacheSize option.
func WithParserCacheSize(v int) ParserOption {
	return func(o *parserOptions) {
		if v <= 0 {
			return
		}
		o.cacheSize = v
	}
}

// WithParserEncryption enables the shouldEncrypt option.
func WithParserEncryption() ParserOption {
	return func(o *parserOptions) {
		o.shouldEncrypt = true
	}
}

// WithParserEncryptionModels sets the encryptionModels option.
func WithParserEncryptionModels(v map[reflect.Type]*EncryptionModel) ParserOption {
	return func(o *parserOptions) {
		o.encryptionModels = v
	}
}

// WithParserEncryptionTagName sets the encryptionTagName option.
func WithParserEncryptionTagName[T interface{ string | *string }](v T) ParserOption {
	return func(o *parserOptions) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.encryptionTagName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.encryptionTagName = vv
		}
	}
}

// WithParserUpdate enables the update option.
func WithParserUpdate() ParserOption {
	return func(o *parserOptions) {
		o.update = true
	}
}

// defaultParserOptions returns the default values for parserOptions.
func defaultParserOptions() *parserOptions {
	return &parserOptions{
		bsonTagName:       DefaultParserBSONTagName,
		cacheSize:         MaxCacheSize,
		encryptionModels:  make(map[reflect.Type]*EncryptionModel),
		encryptionTagName: DefaultParserEncryptionTagName,
	}
}

// newParserOptions creates a new parserOptions with the given options.
func newParserOptions(opts ...ParserOption) *parserOptions {
	o := defaultParserOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
