// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package keyset

import (
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithClock sets the clock option.
func WithClock(v Clock) Option {
	return func(o *options) {
		o.clock = v
	}
}

// WithExpiryDisabled enables the expiryDisabled option.
func WithExpiryDisabled() Option {
	return func(o *options) {
		o.expiryDisabled = true
	}
}

// WithMaxClockSkew sets the maxClockSkew option.
func WithMaxClockSkew(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxClockSkew = v
	}
}

// WithPreviousKeys appends to the previousKeys option.
func WithPreviousKeys(v ...[]byte) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.previousKeys = append(o.previousKeys, v...)
	}
}

// WithTTL sets the ttl option.
func WithTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ttl = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		clock:        defaultClock,
		maxClockSkew: DefaultMaxClockSkew,
		ttl:          DefaultTTL,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
