// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package revocation

import (
	"net/http"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithHttpClient sets the httpClient option.
func WithHttpClient(v *http.Client) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.httpClient = v
	}
}

// WithMaxAttempts sets the maxAttempts option.
func WithMaxAttempts(v int) Option {
	return func(o *options) {
		o.maxAttempts = v
	}
}

// WithMaxCacheEntries sets the maxCacheEntries option.
func WithMaxCacheEntries(v int) Option {
	return func(o *options) {
		o.maxCacheEntries = v
	}
}

// WithMaxTTL sets the maxTTL option.
func WithMaxTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxTTL = v
	}
}

// WithTimeout sets the timeout option.
func WithTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.timeout = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		failMode:        DefaultFailMode,
		maxAttempts:     DefaultMaxAttempts,
		maxCacheEntries: DefaultMaxCacheEntries,
		maxTTL:          DefaultMaxTTL,
		timeout:         DefaultTimeout,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
