// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package tlsle

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/collections/slices"

	"golang.org/x/crypto/acme"
)

// Option is a functional option for configuring options.
type Option func(o *options) error

// WithCacheDir sets the cacheDir option.
func WithCacheDir[T interface{ string | *string }](v T) Option {
	return func(o *options) error {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return nil
			}
			o.cacheDir = vv
		case *string:
			if t == nil {
				return nil
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return nil
			}
			o.cacheDir = vv
		}
		return nil
	}
}

// WithClient sets the client option.
func WithClient(v *acme.Client) Option {
	return func(o *options) error {
		if v == nil {
			return nil
		}
		o.client = v
		return nil
	}
}

// WithDomains sets the domains option.
func WithDomains(v ...string) Option {
	return func(o *options) error {
		if len(v) == 0 {
			return nil
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.domains = transformed
		return nil
	}
}

// WithEmail sets the email option.
func WithEmail[T interface{ string | *string }](v T) Option {
	return func(o *options) error {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return nil
			}
			o.email = vv
		case *string:
			if t == nil {
				return nil
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return nil
			}
			o.email = vv
		}
		return nil
	}
}

// WithHttpShutdownTimeout sets the httpShutdownTimeout option.
func WithHttpShutdownTimeout(v time.Duration) Option {
	return func(o *options) error {
		if v <= 0 {
			return nil
		}
		o.httpShutdownTimeout = v
		return nil
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) error {
		if v == nil {
			return nil
		}
		o.logger = v
		return nil
	}
}

// WithRenewBefore sets the renewBefore option.
func WithRenewBefore(v time.Duration) Option {
	return func(o *options) error {
		if v <= 0 {
			return nil
		}
		o.renewBefore = v
		return nil
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		httpShutdownTimeout: 5 * time.Second,
		logger:              slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) (*options, error) {
	o := defaultOptions()
	for _, opt := range opts {
		if err := opt(o); err != nil {
			return nil, err
		}
	}
	return o, nil
}
