// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package tlsle

//go:generate go run github.com/altessa-s/go-atlas/tools/codegen/optgen generate --type=options --option-error --all-fields

import (
	"errors"
	"log/slog"
	"time"

	"golang.org/x/crypto/acme"
)

var (
	// ErrNoDomains is returned when no domains are configured.
	ErrNoDomains = errors.New("no domains configured")
	// ErrNoEmail is returned when no email is configured.
	ErrNoEmail = errors.New("no email configured")
)

type options struct {
	domains             []string
	cacheDir            string
	email               string
	renewBefore         time.Duration
	client              *acme.Client
	logger              *slog.Logger
	httpShutdownTimeout time.Duration `optgen:"default=5*time.Second"`
}

func (o *options) validate() error {
	// Validate required options
	if len(o.domains) == 0 {
		return ErrNoDomains
	}
	if o.email == "" {
		return ErrNoEmail
	}

	return nil
}

// With* option functions are generated by optgen.
