// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package principal

import (
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithRolesClaim sets the rolesClaim option.
func WithRolesClaim[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.rolesClaim = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.rolesClaim = vv
		}
	}
}

// WithTenantClaim sets the tenantClaim option.
func WithTenantClaim[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.tenantClaim = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.tenantClaim = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		rolesClaim:  DefaultRolesClaim,
		tenantClaim: DefaultTenantClaim,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
