// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package cache

import (
	"log/slog"
	"regexp"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/grpc/interceptors/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCacheDecision sets the cacheDecision option.
func WithCacheDecision(v DecisionFunc) Option {
	return func(o *options) {
		o.cacheDecision = v
	}
}

// WithCacheHeadersEnabled enables the cacheHeadersEnabled option.
func WithCacheHeadersEnabled() Option {
	return func(o *options) {
		o.cacheHeadersEnabled = true
	}
}

// WithCacheTTL sets the cacheTTL option.
func WithCacheTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.cacheTTL = v
	}
}

// WithIgnoreMethods sets the ignoreMethods option.
func WithIgnoreMethods(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignoreMethods = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithKeyGenerator sets the keyGenerator option.
func WithKeyGenerator(v KeyGenerator) Option {
	return func(o *options) {
		o.keyGenerator = v
	}
}

// WithKeysPrefix sets the keysPrefix option.
func WithKeysPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.keysPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.keysPrefix = vv
		}
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMethods sets the methods option.
func WithMethods(v map[string]*MethodConfig) Option {
	return func(o *options) {
		o.methods = v
	}
}

// WithSerializer sets the serializer option.
func WithSerializer(v Serializer) Option {
	return func(o *options) {
		o.serializer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cacheDecision:       DefaultSuccessOnlyDecision(DefaultTTL),
		cacheHeadersEnabled: true,
		cacheTTL:            DefaultTTL,
		ignorePatterns:      defaults.IgnorePatterns,
		keyGenerator:        DefaultKeyGenerator,
		logger:              slog.New(slog.DiscardHandler),
		methods:             make(map[string]*MethodConfig),
		serializer:          NewDefaultSerializer(nil),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
