// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=walkOptions

package files

// Option is a functional option for configuring walkOptions.
type WalkOption func(o *walkOptions)

// WithFollowSymlinks enables the followSymlinks option.
func WithFollowSymlinks() WalkOption {
	return func(o *walkOptions) {
		o.followSymlinks = true
	}
}

// WithMaxDepth sets the maxDepth option.
func WithMaxDepth(v int) WalkOption {
	return func(o *walkOptions) {
		o.maxDepth = v
	}
}

// WithSkipHidden enables the skipHidden option.
func WithSkipHidden() WalkOption {
	return func(o *walkOptions) {
		o.skipHidden = true
	}
}

// defaultWalkOptions returns the default values for walkOptions.
func defaultWalkOptions() *walkOptions {
	return &walkOptions{
		extensions: make(map[string]struct{}),
	}
}

// newWalkOptions creates a new walkOptions with the given options.
func newWalkOptions(opts ...WalkOption) *walkOptions {
	o := defaultWalkOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
