// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/altessa-s/go-atlas/tools/codegen/optgen/model"

	coreerrs "github.com/altessa-s/go-atlas/core/errors"
)

// pluginOptionsTemplate is the top-level text/template that renders a complete
// generated Go source file. It emits the package clause, imports, the Option
// type alias (when requested), per-field With* functions, defaultOptions,
// newOptions, helper functions, and type definitions.
var pluginOptionsTemplate = template.Must(template.New("plugin-options").Funcs(template.FuncMap{
	"trim": strings.TrimSpace,
}).Parse(`// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type={{.TypeName}}

package {{.Package}}

{{if .Imports}}
import (
{{range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{end}}
)
{{end}}

{{if .GenerateOptionType}}
// Option is a functional option for configuring {{.TypeName}}.
type {{.OptionType}}{{.GenericInfo.TypeParamsDecl}} func(o *{{.TypeName}}{{.GenericInfo.TypeParamsNames}}){{if .OptionReturnsError}} error{{end}}

{{end}}
{{if .TypeDefs}}
{{range .TypeDefs}}
{{.}}

{{end}}
{{end}}
{{range .Functions}}
{{if trim .}}
{{.}}

{{end}}
{{end}}
{{if .GenerateDefaultFunc}}
// {{.DefaultFuncName}} returns the default values for {{.TypeName}}.
func {{.DefaultFuncName}}{{.GenericInfo.TypeParamsDecl}}() *{{.TypeName}}{{.GenericInfo.TypeParamsNames}} {
	return &{{.TypeName}}{{.GenericInfo.TypeParamsNames}}{
{{- range .Fields}}
{{- if trim .Default}}
		{{.FieldName}}: {{.Default}},
{{- end}}
{{- end}}
	}
}
{{end}}
{{if .GenerateNewFunc}}
// {{.NewFuncName}} creates a new {{.TypeName}} with the given options.
{{- $g := .GenericInfo}}
{{- $retType := printf "*%s%s" .TypeName $g.TypeParamsNames}}
{{- if .OptionReturnsError}}{{$retType = printf "(%s, error)" $retType}}{{end}}
func {{.NewFuncName}}{{$g.TypeParamsDecl}}(opts ...{{.OptionType}}{{$g.TypeParamsNames}}) {{$retType}} {
	o := {{.DefaultFuncName}}{{.GenericInfo.TypeParamsNames}}()
	for _, opt := range opts {
{{- if .OptionReturnsError}}
		if err := opt(o); err != nil {
			return nil, err
		}
{{- else}}
		opt(o)
{{- end}}
	}
{{- if .NormalizationMethod}}
	o.{{.NormalizationMethod}}()
{{- end}}
{{- if .OptionReturnsError}}
	return o, nil
{{- else}}
	return o
{{- end}}
}
{{end}}

{{if .Helpers}}
{{range .Helpers}}
{{.}}

{{end}}
{{end}}
`))

// renderPluginTemplate executes [pluginOptionsTemplate] with the given data and
// passes the result through go/format.Source. If formatting fails the raw
// template output is discarded and the error is wrapped for debugging.
func (g *Generator) renderPluginTemplate(data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := pluginOptionsTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template execution failed: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		// Keep the raw output to aid debugging.
		return nil, coreerrs.WrapOperation(err, "format generated code")
	}
	return out, nil
}

// Ensure imports use the correct type in template data.
var _ = model.GeneratedImport{}
