// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package landlock

import (
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithReadPaths appends to the readPaths option.
func WithReadPaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.readPaths = append(o.readPaths, transformed...)
	}
}

// WithReadWritePaths appends to the readWritePaths option.
func WithReadWritePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.readWritePaths = append(o.readWritePaths, transformed...)
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
