// Copyright 2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package fieldbehavior

//go:generate go run github.com/altessa-s/go-atlas/cmd/optgen generate

import (
	"google.golang.org/genproto/googleapis/api/annotations"
)

// DefaultStrict is the default value for [WithStrict]. When false (the
// default), Strip silently clears matching fields. When true, Strip returns a
// *BehaviorViolationError listing every populated field that would have been
// cleared, leaving the message unchanged.
const DefaultStrict = false

// DefaultMaxDepth is the default value for [WithMaxDepth]. Protocol Buffers
// schemas may not contain cycles, so 32 levels comfortably exceed any
// realistic resource graph while bounding stack growth on fuzzed input.
const DefaultMaxDepth = 32

// DefaultCreateBehaviors lists the behaviors stripped by [StripCreate]:
// OUTPUT_ONLY and IDENTIFIER are server-managed and must not be supplied
// by the client.
var DefaultCreateBehaviors = []annotations.FieldBehavior{
	annotations.FieldBehavior_OUTPUT_ONLY,
	annotations.FieldBehavior_IDENTIFIER,
}

// DefaultUpdateBehaviors lists the behaviors stripped by [StripUpdate]:
// OUTPUT_ONLY, IDENTIFIER, and IMMUTABLE (the latter prevents callers from
// changing fields fixed at Create time).
var DefaultUpdateBehaviors = []annotations.FieldBehavior{
	annotations.FieldBehavior_OUTPUT_ONLY,
	annotations.FieldBehavior_IDENTIFIER,
	annotations.FieldBehavior_IMMUTABLE,
}

// DefaultResponseBehaviors lists the behaviors stripped by [StripResponse]:
// INPUT_ONLY fields are accepted on input but must not appear in outbound
// responses (passwords, auth tokens, …).
var DefaultResponseBehaviors = []annotations.FieldBehavior{
	annotations.FieldBehavior_INPUT_ONLY,
}

// options carries fieldbehavior configuration. Tunables are generated by
// optgen — never construct this struct directly, use [WithStrict],
// [WithBehaviors], and [WithMaxDepth].
type options struct {
	strict    bool                        `optgen:"default=DefaultStrict"`
	maxDepth  int                         `optgen:"default=DefaultMaxDepth"`
	behaviors []annotations.FieldBehavior `opt:"-"`
}

// WithBehaviors configures the set of google.api.field_behavior values that
// trigger a strip. Calling [Strip] without this option (or with an empty
// slice) makes Strip a no-op. The convenience functions
// [StripCreate]/[StripUpdate]/[StripResponse] preconfigure it from the
// matching Default*Behaviors slice; passing WithBehaviors to them replaces
// that default.
//
// Written by hand rather than generated because optgen does not produce
// variadic setters; the field is tagged opt:"-" so generation skips it.
func WithBehaviors(set ...annotations.FieldBehavior) Option {
	return func(o *options) {
		if len(set) == 0 {
			o.behaviors = nil
			return
		}
		o.behaviors = append(o.behaviors[:0], set...)
	}
}
