// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package fieldbehavior

// Option is a functional option for configuring options.
type Option func(o *options)

// WithMaxDepth sets the maxDepth option.
func WithMaxDepth(v int) Option {
	return func(o *options) {
		o.maxDepth = v
	}
}

// WithStrict enables the strict option.
func WithStrict() Option {
	return func(o *options) {
		o.strict = true
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		maxDepth: DefaultMaxDepth,
		strict:   DefaultStrict,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
