// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package health

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/observability/metrics"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAdaptiveBufferMultiplier sets the adaptiveBufferMultiplier option.
func WithAdaptiveBufferMultiplier(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.adaptiveBufferMultiplier = v
	}
}

// WithAdaptiveBufferThreshold sets the adaptiveBufferThreshold option.
func WithAdaptiveBufferThreshold(v int32) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.adaptiveBufferThreshold = v
	}
}

// WithCheckSchedule sets the checkSchedule option.
func WithCheckSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.checkSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.checkSchedule = vv
		}
	}
}

// WithCheckTimeout sets the checkTimeout option.
func WithCheckTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.checkTimeout = v
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.collector = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxAdaptiveBuffer sets the maxAdaptiveBuffer option.
func WithMaxAdaptiveBuffer(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxAdaptiveBuffer = v
	}
}

// WithMaxConcurrentHealthChecks sets the maxConcurrentHealthChecks option.
func WithMaxConcurrentHealthChecks(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxConcurrentHealthChecks = v
	}
}

// WithMaxWatchersPerService sets the maxWatchersPerService option.
func WithMaxWatchersPerService(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxWatchersPerService = v
	}
}

// WithNumShards sets the numShards option.
func WithNumShards(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.numShards = v
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.scheduler = v
	}
}

// WithStatusCacheTTL sets the statusCacheTTL option.
func WithStatusCacheTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.statusCacheTTL = v
	}
}

// WithWatcherChannelBuffer sets the watcherChannelBuffer option.
func WithWatcherChannelBuffer(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.watcherChannelBuffer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		adaptiveBufferMultiplier:  DefaultAdaptiveBufferMultiplier,
		adaptiveBufferThreshold:   DefaultAdaptiveBufferThreshold,
		checkTimeout:              DefaultCheckTimeout,
		logger:                    slog.New(slog.DiscardHandler),
		maxAdaptiveBuffer:         DefaultMaxAdaptiveBuffer,
		maxConcurrentHealthChecks: DefaultMaxConcurrentHealthChecks,
		maxWatchersPerService:     DefaultMaxWatchersPerService,
		numShards:                 DefaultNumShards,
		statusCacheTTL:            DefaultStatusCacheTTL,
		watcherChannelBuffer:      DefaultWatcherChannelBuffer,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
