// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package plugins

//go:generate go run github.com/altessa-s/go-atlas/tools/codegen/optgen generate

import (
	"log/slog"
	"time"
)

// Default values for plugin manager options.
const (
	DefaultDir           = "./plugins"
	DefaultInitTimeout   = 5 * time.Second
	DefaultWatchDebounce = 200 * time.Millisecond
)

// options contains Manager configuration.
type options struct {
	logger        *slog.Logger
	dir           string         `optgen:"default=DefaultDir"`
	load          []string       `optgen:"append"`
	disabled      []string       `optgen:"append"`
	initTimeout   time.Duration  `optgen:"default=DefaultInitTimeout"`
	watchDebounce time.Duration  `optgen:"default=DefaultWatchDebounce"`
	sandbox       SandboxOptions `optgen:"manual"`
}

// WithSandbox configures Linux process-hardening primitives applied lazily on
// the first [Manager.Load]. See [SandboxOptions] for the threat model and the
// host-wide cost of every primitive.
//
// Manual option (not generated by optgen) because [SandboxOptions] is a
// struct, not a primitive.
func WithSandbox(o SandboxOptions) Option {
	return func(opts *options) {
		opts.sandbox = o
	}
}
