// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package plugins

//go:generate go run github.com/altessa-s/go-atlas/tools/codegen/optgen generate

import (
	"log/slog"
	"slices"
	"time"
)

// Default values for plugin manager options.
const (
	DefaultDir           = "./plugins"
	DefaultInitTimeout   = 5 * time.Second
	DefaultWatchDebounce = 200 * time.Millisecond
)

// options contains Manager configuration.
type options struct {
	logger        *slog.Logger
	dir           string         `optgen:"default=DefaultDir"`
	load          []string       `optgen:"append"`
	disabled      []string       `optgen:"append"`
	initTimeout   time.Duration  `optgen:"default=DefaultInitTimeout"`
	watchDebounce time.Duration  `optgen:"default=DefaultWatchDebounce"`
	sandbox       SandboxOptions `optgen:"manual"`
}

// WithSandbox configures Linux process-hardening primitives applied lazily on
// the first [Manager.Load]. See [SandboxOptions] for the threat model and the
// host-wide cost of every primitive.
//
// WithSandbox clones every slice field inside o ([LandlockOptions.ReadPaths],
// [LandlockOptions.ReadWritePaths], [CapabilitiesOptions.Keep]) so that
// later mutations to the caller's slices cannot reach the manager. This
// matters because operator config is often built incrementally and a
// stale slice header would otherwise let a "Validate then build" sequence
// be subverted by a post-Validate slice append.
//
// Manual option (not generated by optgen) because [SandboxOptions] is a
// struct, not a primitive.
func WithSandbox(o SandboxOptions) Option {
	return func(opts *options) {
		o.Landlock.ReadPaths = slices.Clone(o.Landlock.ReadPaths)
		o.Landlock.ReadWritePaths = slices.Clone(o.Landlock.ReadWritePaths)
		o.Capabilities.Keep = slices.Clone(o.Capabilities.Keep)
		opts.sandbox = o
	}
}
