// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package redis

import (
	"strings"
	"time"
)

// Option is a functional option for configuring a [Storage] instance.
// Pass one or more Option values to [New] to override default behavior.
type Option func(o *options)

// WithHistoryTTL sets the Redis key expiration for each history entry.
// Values less than or equal to zero are ignored, keeping the default of
// [DefaultHistoryTTL] (no expiration). When set, Redis will automatically
// evict history keys after the specified duration, independent of
// [Storage.CleanupHistory].
func WithHistoryTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.historyTTL = v
	}
}

// WithKeyPrefix sets the Redis key prefix prepended to every key managed by
// [Storage]. Empty strings (after trimming whitespace) and nil pointers are
// ignored, keeping the default of [DefaultKeyPrefix]. Trailing colons are
// normalized by [New].
func WithKeyPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.keyPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.keyPrefix = vv
		}
	}
}

// WithMaxHistoryPerTask sets the maximum number of history entries retained
// per task. After each call to [Storage.AddHistory], entries exceeding this
// limit are trimmed on a best-effort basis (oldest first). The default is
// [DefaultMaxHistoryPerTask]. A value of zero or negative disables trimming.
func WithMaxHistoryPerTask(v int) Option {
	return func(o *options) {
		o.maxHistoryPerTask = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		historyTTL:        DefaultHistoryTTL,
		keyPrefix:         DefaultKeyPrefix,
		maxHistoryPerTask: DefaultMaxHistoryPerTask,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
