// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package loader

import (
	"strings"

	loadersecrets "github.com/altessa-s/go-atlas/config/loader/secrets"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithEnvDelimiter sets the envDelimiter option.
func WithEnvDelimiter[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.envDelimiter = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.envDelimiter = vv
		}
	}
}

// WithEnvPrefix sets the envPrefix option.
func WithEnvPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.envPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.envPrefix = vv
		}
	}
}

// WithEnvSectionDelimiter sets the envSectionDelimiter option.
func WithEnvSectionDelimiter[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.envSectionDelimiter = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.envSectionDelimiter = vv
		}
	}
}

// WithPath sets the path option.
func WithPath[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.path = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.path = vv
		}
	}
}

// WithSecretsManager sets the secretsManager option.
func WithSecretsManager(v loadersecrets.Manager) Option {
	return func(o *options) {
		o.secretsManager = v
	}
}

// WithSkipDefaults enables the skipDefaults option.
func WithSkipDefaults() Option {
	return func(o *options) {
		o.skipDefaults = true
	}
}

// WithSkipEnv enables the skipEnv option.
func WithSkipEnv() Option {
	return func(o *options) {
		o.skipEnv = true
	}
}

// WithStructTag sets the structTag option.
func WithStructTag[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.structTag = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.structTag = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		envDelimiter:        DefaultEnvDelimiter,
		envSectionDelimiter: DefaultEnvSectionDelimiter,
		structTag:           DefaultStructTagName,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	o.normalization()
	return o
}
