// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/security/tlsutils"

	vaultApi "github.com/hashicorp/vault/api"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCacheDir sets the cacheDir option.
func WithCacheDir[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.cacheDir = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.cacheDir = vv
		}
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithOcspStapler sets the ocspStapler option.
func WithOcspStapler(v tlsutils.OCSPStapler) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.ocspStapler = v
	}
}

// WithVaultClient sets the vaultClient option.
func WithVaultClient(v *vaultApi.Client) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.vaultClient = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
