// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package dispatch

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option[T any] func(o *options[T])

// WithBackPressure enables the backPressure option.
func WithBackPressure[T any]() Option[T] {
	return func(o *options[T]) {
		o.backPressure = true
	}
}

// WithBatchSize sets the batchSize option.
func WithBatchSize[T any](v int) Option[T] {
	return func(o *options[T]) {
		if v <= 0 {
			return
		}
		o.batchSize = v
	}
}

// WithBufferSize sets the bufferSize option.
func WithBufferSize[T any](v int) Option[T] {
	return func(o *options[T]) {
		if v <= 0 {
			return
		}
		o.bufferSize = v
	}
}

// WithCollector sets the collector option.
func WithCollector[T any](v metrics.Collector) Option[T] {
	return func(o *options[T]) {
		o.collector = v
	}
}

// WithFlushInterval sets the flushInterval option.
func WithFlushInterval[T any](v time.Duration) Option[T] {
	return func(o *options[T]) {
		if v <= 0 {
			return
		}
		o.flushInterval = v
	}
}

// WithLogger sets the logger option.
func WithLogger[T any](v *slog.Logger) Option[T] {
	return func(o *options[T]) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMetricsSubsystem sets the metricsSubsystem option.
func WithMetricsSubsystem[T any](v string) Option[T] {
	return func(o *options[T]) {
		o.metricsSubsystem = strings.TrimSpace(v)
	}
}

// WithOnDrop sets the onDrop option.
func WithOnDrop[T any](v DropHandler[T]) Option[T] {
	return func(o *options[T]) {
		o.onDrop = v
	}
}

// WithRetryAttempts sets the retryAttempts option.
func WithRetryAttempts[T any](v int) Option[T] {
	return func(o *options[T]) {
		if v < 0 {
			return
		}
		o.retryAttempts = v
	}
}

// WithRetryBackoff sets the retryBackoff option.
func WithRetryBackoff[T any](v time.Duration) Option[T] {
	return func(o *options[T]) {
		if v <= 0 {
			return
		}
		o.retryBackoff = v
	}
}

// WithWorkers sets the workers option.
func WithWorkers[T any](v int) Option[T] {
	return func(o *options[T]) {
		if v <= 0 {
			return
		}
		o.workers = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions[T any]() *options[T] {
	return &options[T]{
		batchSize:        DefaultBatchSize,
		bufferSize:       DefaultBufferSize,
		flushInterval:    DefaultFlushInterval,
		logger:           defaultLogger(),
		metricsSubsystem: DefaultMetricsSubsystem,
		retryAttempts:    DefaultRetryAttempts,
		retryBackoff:     DefaultRetryBackoff,
		workers:          DefaultWorkers,
	}
}

// newOptions creates a new options with the given options.
func newOptions[T any](opts ...Option[T]) *options[T] {
	o := defaultOptions[T]()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
