// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package oauth2client

import (
	"log/slog"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"

	"golang.org/x/oauth2"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAuthStyle sets the authStyle option.
func WithAuthStyle(v oauth2.AuthStyle) Option {
	return func(o *options) {
		o.authStyle = v
	}
}

// WithClientAuth sets the clientAuth option.
func WithClientAuth(v ClientAuthenticator) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.clientAuth = v
	}
}

// WithEarlyExpiry sets the earlyExpiry option.
func WithEarlyExpiry(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.earlyExpiry = v
	}
}

// WithEndpointParams sets the endpointParams option.
func WithEndpointParams(v url.Values) Option {
	return func(o *options) {
		o.endpointParams = v
	}
}

// WithHTTPClient sets the httpClient option.
func WithHTTPClient(v *http.Client) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.httpClient = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMetrics sets the metrics option.
func WithMetrics(v *Metrics) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.metrics = v
	}
}

// WithRetryAttempts sets the retryAttempts option.
func WithRetryAttempts(v int) Option {
	return func(o *options) {
		o.retryAttempts = v
	}
}

// WithRetryBaseDelay sets the retryBaseDelay option.
func WithRetryBaseDelay(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryBaseDelay = v
	}
}

// WithRetryMaxDelay sets the retryMaxDelay option.
func WithRetryMaxDelay(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryMaxDelay = v
	}
}

// WithScopes sets the scopes option.
func WithScopes(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.scopes = transformed
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		authStyle:      DefaultAuthStyle,
		logger:         slog.New(slog.DiscardHandler),
		retryAttempts:  DefaultRetryAttempts,
		retryBaseDelay: DefaultRetryBaseDelay,
		retryMaxDelay:  DefaultRetryMaxDelay,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
