// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package prometheus

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/prometheus/client_golang/prometheus"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/transport/http/server/middlewares/defaults"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithEnableSizeMetrics enables the enableSizeMetrics option.
func WithEnableSizeMetrics() Option {
	return func(o *options) {
		o.enableSizeMetrics = true
	}
}

// WithIgnorePaths sets the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = transformed
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithNamespace sets the namespace option.
func WithNamespace[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.namespace = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.namespace = vv
		}
	}
}

// WithRegisterer sets the registerer option.
func WithRegisterer(v prometheus.Registerer) Option {
	return func(o *options) {
		o.registerer = v
	}
}

// WithSubsystem sets the subsystem option.
func WithSubsystem[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.subsystem = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.subsystem = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		ignorePatterns: defaults.IgnorePatterns,
		logger:         slog.New(slog.DiscardHandler),
		namespace:      DefaultNamespace,
		registerer:     prometheus.DefaultRegisterer,
		subsystem:      DefaultSubsystem,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
