// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package outboxstore

import (
	"context"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollectionName sets the collectionName option.
func WithCollectionName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.collectionName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.collectionName = vv
		}
	}
}

// WithContext sets the ctx option.
func WithContext(v context.Context) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.ctx = v
	}
}

// WithIndexCreateTimeout sets the indexTimeout option.
func WithIndexCreateTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.indexTimeout = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		collectionName: DefaultCollectionName,
		indexTimeout:   DefaultIndexCreateTimeout,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
