// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package etag

import (
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithNewHash sets the newHash option.
func WithNewHash(v NewHashFunc) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.newHash = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		newHash: DefaultNewHash,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
