// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package vault

import (
	"crypto/tls"
	"log/slog"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/health"
	"github.com/altessa-s/go-atlas/observability/metrics"
	"github.com/altessa-s/go-atlas/security/vault/auth"

	vaultApi "github.com/hashicorp/vault/api"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAuthMethod sets the authMethod option.
func WithAuthMethod(v auth.Method) Option {
	return func(o *options) {
		o.authMethod = v
	}
}

// WithAuthTimeout sets the authTimeout option.
func WithAuthTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.authTimeout = v
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithHealthCoordinator sets the healthCoordinator option.
func WithHealthCoordinator(v *health.Coordinator) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.healthCoordinator = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithTLSConfig sets the tlsConfig option.
func WithTLSConfig(v *tls.Config) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.tlsConfig = v
	}
}

// WithVaultClient sets the vaultClient option.
func WithVaultClient(v *vaultApi.Client) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.vaultClient = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		authTimeout: DefaultInitialAuthTimeout,
		logger:      slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
