// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package kmsaws

import (
	"crypto/tls"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithEndpoint sets the endpoint option.
func WithEndpoint(v *string) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.endpoint = v
	}
}

// WithRegion sets the region option.
func WithRegion(v *string) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.region = v
	}
}

// WithTLS sets the tLS option.
func WithTLS(v *tls.Config) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.tLS = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
