// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package spool

import (
	"io"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithMaxBytes sets the maxBytes option.
func WithMaxBytes(v int64) Option {
	return func(o *options) {
		o.maxBytes = v
	}
}

// WithMemThreshold sets the memThreshold option.
func WithMemThreshold(v int64) Option {
	return func(o *options) {
		o.memThreshold = v
	}
}

// WithTee sets the tee option.
func WithTee(v io.Writer) Option {
	return func(o *options) {
		o.tee = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		memThreshold: DefaultMemThreshold,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
