// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package gcp

import (
	"github.com/altessa-s/go-atlas/core/runtime/concurrency"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/security/secrets"
	"github.com/altessa-s/go-atlas/security/secrets/codec"
	"github.com/altessa-s/go-atlas/security/secrets/codec/keys/base64"
	"github.com/altessa-s/go-atlas/security/secrets/codec/values/json"
)

// Option is a functional option for configuring options.
type Option[T any] func(o *options[T])

// WithConcurrencyLimitFunc sets the concurrencyLimitFunc option.
func WithConcurrencyLimitFunc[T any](v concurrency.ConcurrencyLimitFunc) Option[T] {
	return func(o *options[T]) {
		if nilcheck.IsNil(v) {
			return
		}
		o.concurrencyLimitFunc = v
	}
}

// WithIgnoreInvalidKeys enables the ignoreInvalidKeys option.
func WithIgnoreInvalidKeys[T any]() Option[T] {
	return func(o *options[T]) {
		o.ignoreInvalidKeys = true
	}
}

// WithKeyDecoder sets the keyDecoder option.
func WithKeyDecoder[T any](v codec.KeyDecoder) Option[T] {
	return func(o *options[T]) {
		if nilcheck.IsNil(v) {
			return
		}
		o.keyDecoder = v
	}
}

// WithLabels sets the labels option.
func WithLabels[T any](v map[string]string) Option[T] {
	return func(o *options[T]) {
		o.labels = v
	}
}

// WithLocker sets the locker option.
func WithLocker[T any](v secrets.Locker) Option[T] {
	return func(o *options[T]) {
		if nilcheck.IsNil(v) {
			return
		}
		o.locker = v
	}
}

// WithValueDecoder sets the valueDecoder option.
func WithValueDecoder[T any](v codec.ValueDecoder[T]) Option[T] {
	return func(o *options[T]) {
		if nilcheck.IsNil(v) {
			return
		}
		o.valueDecoder = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions[T any]() *options[T] {
	return &options[T]{
		keyDecoder:   base64.NewKeyDecoder(),
		labels:       make(map[string]string),
		valueDecoder: json.NewValueDecoder[T](),
	}
}

// newOptions creates a new options with the given options.
func newOptions[T any](opts ...Option[T]) *options[T] {
	o := defaultOptions[T]()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
