// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package nats

import (
	"log/slog"
	"strings"

	"github.com/nats-io/nats.go/jetstream"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBucket sets the bucket option.
func WithBucket[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.bucket = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.bucket = vv
		}
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithRenewRatio sets the renewRatio option.
func WithRenewRatio(v float64) Option {
	return func(o *options) {
		o.renewRatio = v
	}
}

// WithStorage sets the storage option.
func WithStorage(v jetstream.StorageType) Option {
	return func(o *options) {
		o.storage = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		bucket:     DefaultBucket,
		logger:     slog.New(slog.DiscardHandler),
		renewRatio: DefaultRenewRatio,
		storage:    DefaultStorage,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
