// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package factory

import (
	"log/slog"

	"github.com/altessa-s/go-atlas/observability/tracing"

	idempotencydata "github.com/altessa-s/go-atlas/data/idempotency"
	sharedlimiter "github.com/altessa-s/go-atlas/data/limiters"
	tlsproviders "github.com/altessa-s/go-atlas/security/tlsutils/providers"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithIdempotency sets the idempotency option.
func WithIdempotency(v idempotencydata.Idempotency) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.idempotency = v
	}
}

// WithLimiter sets the limiter option.
func WithLimiter(v sharedlimiter.Limiter) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.limiter = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithTlsProviders sets the tlsProviders option.
func WithTlsProviders(v *tlsproviders.Providers) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.tlsProviders = v
	}
}

// WithTracer sets the tracer option.
func WithTracer(v tracing.Tracer) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.tracer = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger: slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
