// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package otlp

import (
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/observability/tracing/adapters"

	grpcclient "github.com/altessa-s/go-atlas/transport/grpc/client"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCompression enables the compression option.
func WithCompression() Option {
	return func(o *options) {
		o.compression = true
	}
}

// WithEndpoint sets the endpoint option.
func WithEndpoint[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.endpoint = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.endpoint = vv
		}
	}
}

// WithEnvironment sets the environment option.
func WithEnvironment[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.environment = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.environment = vv
		}
	}
}

// WithExportTimeout sets the exportTimeout option.
func WithExportTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.exportTimeout = v
	}
}

// WithGRPCClientOptions appends to the grpcClientOptions option.
func WithGRPCClientOptions(v ...grpcclient.Option) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.grpcClientOptions = append(o.grpcClientOptions, v...)
	}
}

// WithHeaders sets the headers option.
func WithHeaders(v map[string]string) Option {
	return func(o *options) {
		o.headers = v
	}
}

// WithInsecure enables the insecure option.
func WithInsecure() Option {
	return func(o *options) {
		o.insecure = true
	}
}

// WithProtocol sets the protocol option.
func WithProtocol(v Protocol) Option {
	return func(o *options) {
		o.protocol = v
	}
}

// WithResourceAttrs sets the resourceAttrs option.
func WithResourceAttrs(v ...adapters.Attribute) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.resourceAttrs = v
	}
}

// WithServiceName sets the serviceName option.
func WithServiceName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceName = vv
		}
	}
}

// WithServiceVersion sets the serviceVersion option.
func WithServiceVersion[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceVersion = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceVersion = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		compression:   DefaultCompression,
		endpoint:      DefaultEndpoint,
		exportTimeout: DefaultExportTimeout,
		headers:       make(map[string]string),
		protocol:      DefaultProtocol,
		serviceName:   DefaultServiceName,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
