// Code generated by "stringer -type=NodeKind,Operator -output=node_string.go"; DO NOT EDIT.

package filter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeKindLiteral-0]
	_ = x[NodeKindIdent-1]
	_ = x[NodeKindBinaryOp-2]
	_ = x[NodeKindUnaryOp-3]
	_ = x[NodeKindCall-4]
	_ = x[NodeKindList-5]
}

const _NodeKind_name = "NodeKindLiteralNodeKindIdentNodeKindBinaryOpNodeKindUnaryOpNodeKindCallNodeKindList"

var _NodeKind_index = [...]uint8{0, 15, 28, 44, 59, 71, 83}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpEqual-0]
	_ = x[OpNotEqual-1]
	_ = x[OpLT-2]
	_ = x[OpLTE-3]
	_ = x[OpGT-4]
	_ = x[OpGTE-5]
	_ = x[OpAnd-6]
	_ = x[OpOr-7]
	_ = x[OpNot-8]
	_ = x[OpIn-9]
	_ = x[OpContains-10]
	_ = x[OpStartsWith-11]
	_ = x[OpEndsWith-12]
	_ = x[OpMatches-13]
	_ = x[OpSize-14]
	_ = x[OpHas-15]
	_ = x[OpExists-16]
	_ = x[OpSubstring-17]
}

const _Operator_name = "OpEqualOpNotEqualOpLTOpLTEOpGTOpGTEOpAndOpOrOpNotOpInOpContainsOpStartsWithOpEndsWithOpMatchesOpSizeOpHasOpExistsOpSubstring"

var _Operator_index = [...]uint8{0, 7, 17, 21, 26, 30, 35, 40, 44, 49, 53, 63, 75, 85, 94, 100, 105, 113, 124}

func (i Operator) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Operator_index)-1 {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[idx]:_Operator_index[idx+1]]
}
