// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=parserConfig

package filter

import (
	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring parserConfig.
type ParserOption func(o *parserConfig)

// WithCustomFunctions sets the customFunctions option.
func WithCustomFunctions(v map[string]CustomFunction) ParserOption {
	return func(o *parserConfig) {
		o.customFunctions = v
	}
}

// WithMaxExpressionLength sets the maxExpressionLength option.
func WithMaxExpressionLength(v int) ParserOption {
	return func(o *parserConfig) {
		if v <= 0 {
			return
		}
		o.maxExpressionLength = v
	}
}

// WithParserCacheSize sets the cacheSize option.
func WithParserCacheSize(v int) ParserOption {
	return func(o *parserConfig) {
		if v <= 0 {
			return
		}
		o.cacheSize = v
	}
}

// WithParserCollector sets the collector option.
func WithParserCollector(v metrics.Collector) ParserOption {
	return func(o *parserConfig) {
		o.collector = v
	}
}

// WithParserNoCache enables the noCache option.
func WithParserNoCache() ParserOption {
	return func(o *parserConfig) {
		o.noCache = true
	}
}

// defaultParserConfig returns the default values for parserConfig.
func defaultParserConfig() *parserConfig {
	return &parserConfig{
		allowedFunctions:    make(map[string]struct{}),
		customFunctions:     make(map[string]CustomFunction),
		maxExpressionLength: DefaultMaxExpressionLength,
		cacheSize:           DefaultParserCacheSize,
	}
}

// newParserConfig creates a new parserConfig with the given options.
func newParserConfig(opts ...ParserOption) *parserConfig {
	o := defaultParserConfig()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
