// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=translatorOptions

package filter

// Option is a functional option for configuring translatorOptions.
type TranslatorOption func(o *translatorOptions)

// WithMaxDepth sets the maxDepth option.
func WithMaxDepth(v int) TranslatorOption {
	return func(o *translatorOptions) {
		if v <= 0 {
			return
		}
		o.maxDepth = v
	}
}

// WithMaxOperations sets the maxOperations option.
func WithMaxOperations(v int) TranslatorOption {
	return func(o *translatorOptions) {
		if v <= 0 {
			return
		}
		o.maxOperations = v
	}
}

// WithMaxRegexLength sets the maxRegexLength option.
func WithMaxRegexLength(v int) TranslatorOption {
	return func(o *translatorOptions) {
		if v <= 0 {
			return
		}
		o.maxRegexLength = v
	}
}

// WithStrictMode enables the strictMode option.
func WithStrictMode() TranslatorOption {
	return func(o *translatorOptions) {
		o.strictMode = true
	}
}

// WithUntrustedInput enables the untrustedInput option.
func WithUntrustedInput() TranslatorOption {
	return func(o *translatorOptions) {
		o.untrustedInput = true
	}
}

// defaultTranslatorOptions returns the default values for translatorOptions.
func defaultTranslatorOptions() *translatorOptions {
	return &translatorOptions{
		maxDepth:       DefaultMaxDepth,
		maxOperations:  DefaultMaxOperations,
		maxRegexLength: DefaultMaxRegexLength,
	}
}

// newTranslatorOptions creates a new translatorOptions with the given options.
func newTranslatorOptions(opts ...TranslatorOption) *translatorOptions {
	o := defaultTranslatorOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
