// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package signals

import (
	"os"
	"time"
)

// Option is a functional option that configures a [Signal] instance
// created by [New].
type Option func(o *options)

// WithErrorHandler sets the [ErrorHandler] invoked when a handler returns an
// error, panics, or exceeds its timeout.
func WithErrorHandler(v ErrorHandler) Option {
	return func(o *options) {
		o.errorHandler = v
	}
}

// WithExecutionMode sets the [ExecutionMode] that determines whether handlers
// run sequentially ([SequentialMode], the default) or in parallel ([ParallelMode]).
func WithExecutionMode(v ExecutionMode) Option {
	return func(o *options) {
		o.executionMode = v
	}
}

// WithHandlerTimeout sets the maximum duration each [ContextHandler] is
// allowed to run before a [*TimeoutError] is reported. Non-positive values
// are ignored and the default ([DefaultHandlerTimeout]) applies.
func WithHandlerTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.handlerTimeout = v
	}
}

// WithShutdownTimeout sets the maximum time [Signal.Shutdown] waits for
// in-flight handlers to complete. Non-positive values are ignored and the
// default ([DefaultShutdownTimeout]) applies.
func WithShutdownTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.shutdownTimeout = v
	}
}

// WithSignalChannelBuffer sets the buffer size of the internal OS signal
// channel. Increasing this value reduces the chance of dropped signals under
// heavy load.
func WithSignalChannelBuffer(v int) Option {
	return func(o *options) {
		o.signalChannelBuffer = v
	}
}

// WithSignals specifies the OS signals the [Signal] handler should listen for.
// An empty list is a no-op.
func WithSignals(v ...os.Signal) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.signals = v
	}
}

// WithWorkerPoolSize sets the maximum number of goroutines that can execute
// signal handlers concurrently. When the pool is exhausted, incoming signals
// are reported to the [ErrorHandler] as dropped.
func WithWorkerPoolSize(v int) Option {
	return func(o *options) {
		o.workerPoolSize = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		executionMode:       SequentialMode,
		handlerTimeout:      DefaultHandlerTimeout,
		shutdownTimeout:     DefaultShutdownTimeout,
		signalChannelBuffer: DefaultSignalChannelBuffer,
		workerPoolSize:      DefaultWorkerPoolSize,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
