// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package signals

import (
	"os"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithErrorHandler sets the errorHandler option.
func WithErrorHandler(v ErrorHandler) Option {
	return func(o *options) {
		o.errorHandler = v
	}
}

// WithExecutionMode sets the executionMode option.
func WithExecutionMode(v ExecutionMode) Option {
	return func(o *options) {
		o.executionMode = v
	}
}

// WithHandlerTimeout sets the handlerTimeout option.
func WithHandlerTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.handlerTimeout = v
	}
}

// WithShutdownTimeout sets the shutdownTimeout option.
func WithShutdownTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.shutdownTimeout = v
	}
}

// WithSignalChannelBuffer sets the signalChannelBuffer option.
func WithSignalChannelBuffer(v int) Option {
	return func(o *options) {
		o.signalChannelBuffer = v
	}
}

// WithSignals sets the signals option.
func WithSignals(v ...os.Signal) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.signals = v
	}
}

// WithWorkerPoolSize sets the workerPoolSize option.
func WithWorkerPoolSize(v int) Option {
	return func(o *options) {
		o.workerPoolSize = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		executionMode:       SequentialMode,
		handlerTimeout:      DefaultHandlerTimeout,
		shutdownTimeout:     DefaultShutdownTimeout,
		signalChannelBuffer: DefaultSignalChannelBuffer,
		workerPoolSize:      DefaultWorkerPoolSize,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
