// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package client

import (
	"crypto/tls"
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/transport/grpc/client/pool"

	"google.golang.org/grpc"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAppName sets the appName option.
func WithAppName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.appName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.appName = vv
		}
	}
}

// WithDialOptions appends to the extraDialOptions option.
func WithDialOptions(v ...grpc.DialOption) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.extraDialOptions = append(o.extraDialOptions, v...)
	}
}

// WithErrorConverter sets the errorConverter option.
func WithErrorConverter(v ErrorConverter) Option {
	return func(o *options) {
		o.errorConverter = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMutationTimeout sets the mutationTimeout option.
func WithMutationTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.mutationTimeout = v
	}
}

// WithPool sets the pool option.
func WithPool(v *pool.ConnectionPool) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.pool = v
	}
}

// WithProxyFunc sets the proxy option.
func WithProxyFunc(v ProxyFunc) Option {
	return func(o *options) {
		o.proxy = v
	}
}

// WithProxyTLSConfig sets the proxyTLSConfig option.
func WithProxyTLSConfig(v *tls.Config) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.proxyTLSConfig = v
	}
}

// WithQueryTimeout sets the queryTimeout option.
func WithQueryTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.queryTimeout = v
	}
}

// WithTlsConfig sets the tlsConfig option.
func WithTlsConfig(v *tls.Config) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.tlsConfig = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:          slog.New(slog.DiscardHandler),
		mutationTimeout: DefaultMutationTimeout,
		queryTimeout:    DefaultQueryTimeout,
		tlsConfig:       defaultSecureTLSConfig(),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
