// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package memory

import (
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCleanupSchedule sets the cleanupSchedule option.
func WithCleanupSchedule[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.cleanupSchedule = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.cleanupSchedule = vv
		}
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.scheduler = v
	}
}

// WithTtl sets the ttl option.
func WithTtl(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ttl = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		ttl: DefaultTTL,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
