// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package wal

import (
	"log/slog"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithFsyncInterval sets the fsyncInterval option.
func WithFsyncInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.fsyncInterval = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxBytes sets the maxBytes option.
func WithMaxBytes(v int64) Option {
	return func(o *options) {
		o.maxBytes = v
	}
}

// WithMaxSegmentBytes sets the maxSegmentBytes option.
func WithMaxSegmentBytes(v int64) Option {
	return func(o *options) {
		o.maxSegmentBytes = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		fsyncInterval:   DefaultFsyncInterval,
		logger:          slog.New(slog.DiscardHandler),
		maxSegmentBytes: DefaultMaxSegmentBytes,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
