// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package httpsign

// Option is a functional option for configuring options.
type Option func(o *options)

// WithErrorHandler sets the errorHandler option.
func WithErrorHandler(v ErrorHandler) Option {
	return func(o *options) {
		o.errorHandler = v
	}
}

// WithMaxBytes sets the maxBytes option.
func WithMaxBytes(v int64) Option {
	return func(o *options) {
		o.maxBytes = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		errorHandler: defaultErrorHandler,
		maxBytes:     DefaultMaxBytes,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
