// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package clickhouse

import (
	"log/slog"
	"strings"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAutoCreateTable enables the autoCreateTable option.
func WithAutoCreateTable() Option {
	return func(o *options) {
		o.autoCreateTable = true
	}
}

// WithCluster sets the cluster option.
func WithCluster[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.cluster = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.cluster = vv
		}
	}
}

// WithDDLTimeout sets the ddlTimeout option.
func WithDDLTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ddlTimeout = v
	}
}

// WithEngine sets the engine option.
func WithEngine[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.engine = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.engine = vv
		}
	}
}

// WithFinal enables the final option.
func WithFinal() Option {
	return func(o *options) {
		o.final = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxBatchSize sets the maxBatchSize option.
func WithMaxBatchSize(v int) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.maxBatchSize = v
	}
}

// WithTTL sets the ttl option.
func WithTTL(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.ttl = v
	}
}

// WithTableName sets the tableName option.
func WithTableName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.tableName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.tableName = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		ddlTimeout:          DefaultDDLTimeout,
		engine:              DefaultEngine,
		logger:              slog.New(slog.DiscardHandler),
		maxBatchSize:        DefaultMaxBatchSize,
		schemaCheckMode:     DefaultSchemaCheckMode,
		schemaMigrationMode: DefaultSchemaMigrationMode,
		tableName:           DefaultTableName,
		timeRangeMode:       DefaultTimeRangeMode,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
