// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package audit

// Option is a functional option for configuring options.
type Option func(o *options)

// WithFailureMode sets the failureMode option.
func WithFailureMode(v FailureMode) Option {
	return func(o *options) {
		o.failureMode = v
	}
}

// WithPolicyMode sets the policyMode option.
func WithPolicyMode(v PolicyMode) Option {
	return func(o *options) {
		o.policyMode = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		failureMode: DefaultFailureMode,
		policyMode:  DefaultPolicyMode,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
