// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package colorized

import (
	"log/slog"
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithAddSource enables the addSource option.
func WithAddSource() Option {
	return func(o *options) {
		o.addSource = true
	}
}

// WithAttributeColors sets the attributeColors option.
func WithAttributeColors(v map[string][]int) Option {
	return func(o *options) {
		o.attributeColors = v
	}
}

// WithLevel sets the level option.
func WithLevel(v slog.Leveler) Option {
	return func(o *options) {
		o.level = v
	}
}

// WithNoColor enables the noColor option.
func WithNoColor() Option {
	return func(o *options) {
		o.noColor = true
	}
}

// WithPrefixAttributeKey sets the prefixAttributeKey option.
func WithPrefixAttributeKey[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.prefixAttributeKey = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.prefixAttributeKey = vv
		}
	}
}

// WithTimeFormat sets the timeFormat option.
func WithTimeFormat[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.timeFormat = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.timeFormat = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		attributeColors: make(map[string][]int),
		level:           DefaultLogLevel,
		timeFormat:      DefaultTimeFormat,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
