// Copyright 2021-2026 ALTESSA SOLUTIONS INC. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

package behavior

import "github.com/altessa-s/go-atlas/core/types/bits"

//go:generate go run github.com/altessa-s/go-atlas/cmd/optgen generate

// DefaultStrict is the default value for [WithStrict]. When false (the
// default), Strip silently clears matching fields. When true, Strip returns a
// *ViolationError listing every populated field that would have been cleared,
// leaving the struct unchanged.
const DefaultStrict = false

// DefaultSchemaWalk is the default value for [WithSchemaWalk]. When false (the
// default), the walk binds instance values and stops at absent nested values.
// When true, the walk resolves nested struct types even when the value is
// absent, yielding a type-complete [Object].
const DefaultSchemaWalk = false

// DefaultMaxDepth is the default value for [WithMaxDepth]. It bounds traversal
// of nested structs to guard against self-referential graphs while comfortably
// exceeding any realistic resource depth. [Strip] clamps the configured value
// to a minimum of 1 so a flat struct is never rejected.
const DefaultMaxDepth = 32

// DefaultPooling is the default value for [WithPooling]. When false (the
// default) every [Engine.Translate] builds its resolved tree on fresh heap
// memory that the GC reclaims together with the tree. When true the engine
// recycles the tree's storage through an internal pool, eliminating the walk's
// allocations on hot paths — at the price of the [Translator] retention rule:
// the translator must not keep any part of the tree after Translate returns.
// [Strip] and [Clean] always pool internally; their tree never escapes the
// call.
const DefaultPooling = false

// DefaultTagName is the default struct tag key read by [Strip], overridable
// with [WithTagName]. Tag names are expected to be a small set of compile-time
// constants: parsed metadata is cached per (type, tag name), so passing dynamic
// strings to [WithTagName] would grow that cache without bound.
const DefaultTagName = "behavior"

// DefaultCreateKinds lists the kinds stripped by [StripCreate]:
// OutputOnly and Identifier are server-managed and must not be supplied by the
// client.
var DefaultCreateKinds = []Kind{OutputOnly, Identifier}

// DefaultUpdateKinds lists the kinds stripped by [StripUpdate]:
// OutputOnly, Identifier, and Immutable (the latter prevents callers from
// changing fields fixed at creation).
var DefaultUpdateKinds = []Kind{OutputOnly, Identifier, Immutable}

// DefaultResponseKinds lists the kinds stripped by [StripResponse]:
// InputOnly fields are accepted on input but must not appear in responses.
var DefaultResponseKinds = []Kind{InputOnly}

// options carries behavior configuration. Tunables are generated by optgen —
// never construct this struct directly, use [WithStrict], [WithSchemaWalk],
// [WithMaxDepth], [WithTagName], and [WithKinds].
type options struct {
	strict     bool   `optgen:"default=DefaultStrict"`
	schemaWalk bool   `optgen:"default=DefaultSchemaWalk"`
	pooling    bool   `optgen:"default=DefaultPooling"`
	maxDepth   int    `optgen:"default=DefaultMaxDepth"`
	tagName    string `optgen:"default=DefaultTagName"`
	kinds      []Kind `opt:"-"`
	// kindsMask mirrors kinds as a bit set; maintained by [WithKinds] so resolve
	// can gate the strip check with a single AND per field.
	kindsMask uint8 `opt:"-"`
}

// WithKinds configures the set of kinds that trigger a strip. Calling
// [Strip] without this option (or with an empty slice) makes Strip a no-op. The
// convenience functions [StripCreate]/[StripUpdate]/[StripResponse] preconfigure
// it from the matching Default*Kinds slice; passing WithKinds to them
// replaces that default.
//
// Written by hand rather than generated because optgen does not produce
// variadic setters; the field is tagged opt:"-" so generation skips it.
func WithKinds(set ...Kind) Option {
	return func(o *options) {
		o.setKinds(set)
	}
}

// setKinds replaces the strip set with a copy of set (so later mutations can
// never write into a caller-shared slice such as DefaultUpdateKinds) and
// rebuilds the mirror bit mask. An empty set clears both.
func (o *options) setKinds(set []Kind) {
	if len(set) == 0 {
		o.kinds = nil
		o.kindsMask = 0
		return
	}
	o.kinds = append(o.kinds[:0], set...)
	o.kindsMask = 0
	for _, k := range o.kinds {
		o.kindsMask = bits.SetBit(o.kindsMask, uint64(k))
	}
}
