// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package behavior

import (
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithMaxDepth sets the maxDepth option.
func WithMaxDepth(v int) Option {
	return func(o *options) {
		o.maxDepth = v
	}
}

// WithPooling enables the pooling option.
func WithPooling() Option {
	return func(o *options) {
		o.pooling = true
	}
}

// WithSchemaWalk enables the schemaWalk option.
func WithSchemaWalk() Option {
	return func(o *options) {
		o.schemaWalk = true
	}
}

// WithStrict enables the strict option.
func WithStrict() Option {
	return func(o *options) {
		o.strict = true
	}
}

// WithTagName sets the tagName option.
func WithTagName[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.tagName = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.tagName = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		maxDepth:   DefaultMaxDepth,
		pooling:    DefaultPooling,
		schemaWalk: DefaultSchemaWalk,
		strict:     DefaultStrict,
		tagName:    DefaultTagName,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
