// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package leveled

import (
	"log/slog"
	"strings"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithDefaultLevel sets the defaultLevel option.
func WithDefaultLevel(v slog.Level) Option {
	return func(o *options) {
		o.defaultLevel = v
	}
}

// WithSubsystemKey sets the subsystemKey option.
func WithSubsystemKey[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.subsystemKey = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.subsystemKey = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		defaultLevel:    DefaultLevel,
		subsystemKey:    DefaultSubsystemKey,
		subsystemLevels: make(map[string]slog.Level),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
