// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package oidc

import (
	"log/slog"
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
	"github.com/altessa-s/go-atlas/observability/health"
	"github.com/altessa-s/go-atlas/observability/metrics"

	corescheduler "github.com/altessa-s/go-atlas/core/scheduler"
	httpclient "github.com/altessa-s/go-atlas/transport/http/client"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithActiveTokensCacheKeyPrefix sets the activeTokensCacheKeyPrefix option.
func WithActiveTokensCacheKeyPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.activeTokensCacheKeyPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.activeTokensCacheKeyPrefix = vv
		}
	}
}

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.collector = v
	}
}

// WithHTTPClientOptions appends to the httpClientOptions option.
func WithHTTPClientOptions(v ...httpclient.Option) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.httpClientOptions = append(o.httpClientOptions, v...)
	}
}

// WithHealthCoordinator sets the healthCoordinator option.
func WithHealthCoordinator(v *health.Coordinator) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.healthCoordinator = v
	}
}

// WithJwksHTTPTimeout sets the jwksHTTPTimeout option.
func WithJwksHTTPTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.jwksHTTPTimeout = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithPresetRules sets the presetRules option.
func WithPresetRules(v ...PresetRule) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		o.presetRules = v
	}
}

// WithRevocationFilter sets the revocationFilter option.
func WithRevocationFilter(v Filter) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.revocationFilter = v
	}
}

// WithRevocationItemType sets the revocationItemType option.
func WithRevocationItemType[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.revocationItemType = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.revocationItemType = vv
		}
	}
}

// WithRevocationLoader sets the revocationLoader option.
func WithRevocationLoader(v DataLoader) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.revocationLoader = v
	}
}

// WithRevocationStorage sets the revocationStorage option.
func WithRevocationStorage(v RevocationStorage) Option {
	return func(o *options) {
		o.revocationStorage = v
	}
}

// WithRevokedTokensCacheKeyPrefix sets the revokedTokensCacheKeyPrefix option.
func WithRevokedTokensCacheKeyPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.revokedTokensCacheKeyPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.revokedTokensCacheKeyPrefix = vv
		}
	}
}

// WithScheduler sets the scheduler option.
func WithScheduler(v corescheduler.TaskRegistrar) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.scheduler = v
	}
}

// WithServiceConfigPath sets the serviceConfigPath option.
func WithServiceConfigPath[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.serviceConfigPath = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.serviceConfigPath = vv
		}
	}
}

// WithTokenCache sets the tokenCache option.
func WithTokenCache(v Cacher) Option {
	return func(o *options) {
		o.tokenCache = v
	}
}

// WithTokensCacheKeyPrefix sets the tokensCacheKeyPrefix option.
func WithTokensCacheKeyPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.tokensCacheKeyPrefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.tokensCacheKeyPrefix = vv
		}
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		activeTokensCacheKeyPrefix:  DefaultActiveTokensCacheKeyPrefix,
		jwksHTTPTimeout:             DefaultJWKSHTTPTimeout,
		logger:                      slog.New(slog.DiscardHandler),
		revocationItemType:          DefaultRevocationItemType,
		revokedTokensCacheKeyPrefix: DefaultRevokedTokensCacheKeyPrefix,
		tokensCacheKeyPrefix:        DefaultTokensCacheKeyPrefix,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
