// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=verifierOptions

package oidc

import (
	"strings"
	"time"

	"github.com/altessa-s/go-atlas/core/collections/slices"
)

// Option is a functional option for configuring verifierOptions.
type ValidationOption func(o *verifierOptions)

// WithValidationAllowMissingSubject enables the allowMissingSubject option.
func WithValidationAllowMissingSubject() ValidationOption {
	return func(o *verifierOptions) {
		o.allowMissingSubject = true
	}
}

// WithValidationAllowedAuthorizedParties sets the allowedAuthorizedParties option.
func WithValidationAllowedAuthorizedParties(v ...string) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.allowedAuthorizedParties = transformed
	}
}

// WithValidationAllowedClientIDs sets the allowedClientIDs option.
func WithValidationAllowedClientIDs(v ...string) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.allowedClientIDs = transformed
	}
}

// WithValidationAudience sets the audience option.
func WithValidationAudience(v ...string) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.audience = transformed
	}
}

// WithValidationCelRules sets the celRules option.
func WithValidationCelRules(v ...CELValidationRule) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		o.celRules = v
	}
}

// WithoutValidationClaimsValidation disables the withoutClaimsValidation option.
func WithoutValidationClaimsValidation() ValidationOption {
	return func(o *verifierOptions) {
		o.withoutClaimsValidation = true
	}
}

// WithValidationExpectedClaims sets the expectedClaims option.
func WithValidationExpectedClaims(v map[string]string) ValidationOption {
	return func(o *verifierOptions) {
		o.expectedClaims = v
	}
}

// WithValidationExpirationRequired enables the expirationRequired option.
func WithValidationExpirationRequired() ValidationOption {
	return func(o *verifierOptions) {
		o.expirationRequired = true
	}
}

// WithValidationIgnoredClaims sets the ignoredClaims option.
func WithValidationIgnoredClaims(v ...string) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignoredClaims = transformed
	}
}

// WithValidationIssuedAt enables the issuedAt option.
func WithValidationIssuedAt() ValidationOption {
	return func(o *verifierOptions) {
		o.issuedAt = true
	}
}

// WithValidationIssuer sets the issuer option.
func WithValidationIssuer[T interface{ string | *string }](v T) ValidationOption {
	return func(o *verifierOptions) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.issuer = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.issuer = vv
		}
	}
}

// WithValidationLeeway sets the leeway option.
func WithValidationLeeway(v time.Duration) ValidationOption {
	return func(o *verifierOptions) {
		if v <= 0 {
			return
		}
		o.leeway = v
	}
}

// WithValidationMaxTokenLifetime sets the maxTokenLifetime option.
func WithValidationMaxTokenLifetime(v time.Duration) ValidationOption {
	return func(o *verifierOptions) {
		if v <= 0 {
			return
		}
		o.maxTokenLifetime = v
	}
}

// WithValidationNotBeforeRequired enables the notBeforeRequired option.
func WithValidationNotBeforeRequired() ValidationOption {
	return func(o *verifierOptions) {
		o.notBeforeRequired = true
	}
}

// WithValidationRequireAuthorizedParty enables the requireAuthorizedParty option.
func WithValidationRequireAuthorizedParty() ValidationOption {
	return func(o *verifierOptions) {
		o.requireAuthorizedParty = true
	}
}

// WithValidationRequiredClaims sets the requiredClaims option.
func WithValidationRequiredClaims(v ...string) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.requiredClaims = transformed
	}
}

// WithValidationRequiredScopes sets the requiredScopes option.
func WithValidationRequiredScopes(v ...string) ValidationOption {
	return func(o *verifierOptions) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.requiredScopes = transformed
	}
}

// WithValidationSubject sets the subject option.
func WithValidationSubject[T interface{ string | *string }](v T) ValidationOption {
	return func(o *verifierOptions) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.subject = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.subject = vv
		}
	}
}

// defaultVerifierOptions returns the default values for verifierOptions.
func defaultVerifierOptions() *verifierOptions {
	return &verifierOptions{
		expectedClaims: make(map[string]string),
	}
}

// newVerifierOptions creates a new verifierOptions with the given options.
func newVerifierOptions(opts ...ValidationOption) *verifierOptions {
	o := defaultVerifierOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
