// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package audit

import (
	"log/slog"
	"time"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBackPressure enables the backPressure option.
func WithBackPressure() Option {
	return func(o *options) {
		o.backPressure = true
	}
}

// WithBatchSize sets the batchSize option.
func WithBatchSize(v int) Option {
	return func(o *options) {
		o.batchSize = v
	}
}

// WithBufferSize sets the bufferSize option.
func WithBufferSize(v int) Option {
	return func(o *options) {
		o.bufferSize = v
	}
}

// WithFlushInterval sets the flushInterval option.
func WithFlushInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.flushInterval = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithOnDrop sets the onDrop option.
func WithOnDrop(v DropHandler) Option {
	return func(o *options) {
		o.onDrop = v
	}
}

// WithRetryAttempts sets the retryAttempts option.
func WithRetryAttempts(v int) Option {
	return func(o *options) {
		o.retryAttempts = v
	}
}

// WithRetryBackoff sets the retryBackoff option.
func WithRetryBackoff(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.retryBackoff = v
	}
}

// WithServiceInfo sets the serviceInfo option.
func WithServiceInfo(v ServiceInfo) Option {
	return func(o *options) {
		o.serviceInfo = v
	}
}

// WithShutdownTimeout sets the shutdownTimeout option.
func WithShutdownTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.shutdownTimeout = v
	}
}

// WithWorkers sets the workers option.
func WithWorkers(v int) Option {
	return func(o *options) {
		o.workers = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		batchSize:       DefaultBatchSize,
		bufferSize:      DefaultBufferSize,
		flushInterval:   DefaultFlushInterval,
		logger:          slog.New(slog.DiscardHandler),
		retryAttempts:   DefaultRetryAttempts,
		retryBackoff:    DefaultRetryBackoff,
		shutdownTimeout: DefaultShutdownTimeout,
		workers:         DefaultWorkers,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
