// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package audit

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/observability/metrics"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCollector sets the collector option.
func WithCollector(v metrics.Collector) Option {
	return func(o *options) {
		o.collector = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMetricsSubsystem sets the metricsSubsystem option.
func WithMetricsSubsystem[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.metricsSubsystem = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.metricsSubsystem = vv
		}
	}
}

// WithServiceInfo sets the serviceInfo option.
func WithServiceInfo(v ServiceInfo) Option {
	return func(o *options) {
		o.serviceInfo = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:           slog.New(slog.DiscardHandler),
		metricsSubsystem: DefaultMetricsSubsystem,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
