// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package s3

import (
	"log/slog"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/core/types/nilcheck"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithBucket sets the bucket option.
func WithBucket[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.bucket = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.bucket = vv
		}
	}
}

// WithExtensions sets the extensions option.
func WithExtensions(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.extensions = transformed
	}
}

// WithIncludeData enables the includeData option.
func WithIncludeData() Option {
	return func(o *options) {
		o.includeData = true
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithPrefix sets the prefix option.
func WithPrefix[T interface{ string | *string }](v T) Option {
	return func(o *options) {
		switch t := any(v).(type) {
		case string:
			vv := strings.TrimSpace(t)
			if vv == "" {
				return
			}
			o.prefix = vv
		case *string:
			if t == nil {
				return
			}
			vv := strings.TrimSpace(*t)
			if vv == "" {
				return
			}
			o.prefix = vv
		}
	}
}

// WithS3Client sets the s3Client option.
func WithS3Client(v S3API) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.s3Client = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		extensions: DefaultExtensions,
		logger:     slog.New(slog.DiscardHandler),
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
