// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/cmd/optgen --type=options

package tracing

import (
	"log/slog"
	"regexp"
	"strings"

	"github.com/altessa-s/go-atlas/core/collections/slices"
	"github.com/altessa-s/go-atlas/observability/tracing/propagation"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithIgnorePaths appends to the ignorePaths option.
func WithIgnorePaths(v ...string) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		transformed := make([]string, len(v))
		for i, val := range v {
			transformed[i] = strings.TrimSpace(val)
		}
		transformed = slices.Deduplicate(transformed)
		o.ignorePaths = append(o.ignorePaths, transformed...)
	}
}

// WithIgnorePatterns sets the ignorePatterns option.
func WithIgnorePatterns(v ...*regexp.Regexp) Option {
	return func(o *options) {
		if len(v) == 0 {
			return
		}
		v = slices.Deduplicate(v)
		o.ignorePatterns = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithPropagator sets the propagator option.
func WithPropagator(v propagation.TextMapPropagator) Option {
	return func(o *options) {
		o.propagator = v
	}
}

// WithSpanNameFunc sets the spanNameFunc option.
func WithSpanNameFunc(v SpanNameFunc) Option {
	return func(o *options) {
		o.spanNameFunc = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		logger:       slog.New(slog.DiscardHandler),
		propagator:   defaultPropagator(),
		spanNameFunc: defaultSpanName,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
