// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package scheduler

import (
	"log/slog"
	"time"

	"github.com/altessa-s/go-atlas/core/types/nilcheck"
)

// Option is a functional option for configuring options.
type Option func(o *options)

// WithCleanupInterval sets the cleanupInterval option.
func WithCleanupInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.cleanupInterval = v
	}
}

// WithHistoryRetention sets the historyRetention option.
func WithHistoryRetention(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.historyRetention = v
	}
}

// WithLeaderElector sets the leaderElector option.
func WithLeaderElector(v LeaderElector) Option {
	return func(o *options) {
		if nilcheck.IsNil(v) {
			return
		}
		o.leaderElector = v
	}
}

// WithLogger sets the logger option.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxConcurrentTasks sets the maxConcurrentTasks option.
func WithMaxConcurrentTasks(v int) Option {
	return func(o *options) {
		o.maxConcurrentTasks = v
	}
}

// WithReservedHighPrioritySlots sets the reservedHighPrioritySlots option.
func WithReservedHighPrioritySlots(v int) Option {
	return func(o *options) {
		o.reservedHighPrioritySlots = v
	}
}

// WithStaleTaskTimeout sets the staleTaskTimeout option.
func WithStaleTaskTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.staleTaskTimeout = v
	}
}

// WithTickInterval sets the tickInterval option.
func WithTickInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.tickInterval = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cleanupInterval:           DefaultCleanupInterval,
		historyRetention:          DefaultHistoryRetention,
		logger:                    slog.New(slog.DiscardHandler),
		maxConcurrentTasks:        DefaultMaxConcurrentTasks,
		reservedHighPrioritySlots: DefaultReservedHighPrioritySlots,
		staleTaskTimeout:          DefaultStaleTaskTimeout,
		tickInterval:              DefaultTickInterval,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
