// Code generated by optgen. DO NOT EDIT.
// Source: go run github.com/altessa-s/go-atlas/tools/codegen/optgen --type=options

package scheduler

import (
	"log/slog"
	"time"

	"github.com/altessa-s/go-atlas/data/leadelect"
)

// Option is a functional option for configuring a [Scheduler] created by [New].
// Options are applied in order; later options override earlier ones for the
// same field.
type Option func(o *options)

// WithCleanupInterval sets how often the scheduler purges expired history
// entries. Non-positive values are ignored.
// Default: [DefaultCleanupInterval] (1 hour).
func WithCleanupInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.cleanupInterval = v
	}
}

// WithHistoryRetention sets the duration for which task execution history is kept
// before being purged by the periodic cleanup routine. Non-positive values are
// ignored. Default: [DefaultHistoryRetention] (7 days).
func WithHistoryRetention(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.historyRetention = v
	}
}

// WithLeaderElector enables distributed leader election so that tasks only
// execute on the current leader node. When set, the scheduler checks
// [Scheduler.IsLeader] before each tick and skips execution on non-leader nodes.
// A nil value is ignored.
func WithLeaderElector(v leadelect.LeaderElector) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.leaderElector = v
	}
}

// WithLogger sets the structured logger used for scheduler lifecycle, task
// execution, and error messages. A nil value is ignored; by default the
// scheduler uses a discard logger.
func WithLogger(v *slog.Logger) Option {
	return func(o *options) {
		if v == nil {
			return
		}
		o.logger = v
	}
}

// WithMaxConcurrentTasks sets the static upper bound on concurrent task
// executions in shared-pool mode. The value is split between a shared pool
// (for Normal and Low priority) and reserved high-priority slots (see
// [WithReservedHighPrioritySlots]). Zero means unlimited concurrency.
// Default: [DefaultMaxConcurrentTasks].
//
// This option is ignored when [WithConcurrencyLimitFunc] is also set, because
// the dynamic limit function takes precedence.
func WithMaxConcurrentTasks(v int) Option {
	return func(o *options) {
		o.maxConcurrentTasks = v
	}
}

// WithReservedHighPrioritySlots sets the number of concurrency slots reserved
// exclusively for [TaskPriorityHigh] tasks. These slots cannot be consumed by
// Normal or Low priority tasks. In static mode the reserved slots are subtracted
// from [WithMaxConcurrentTasks]; in dynamic mode they are enforced at dispatch
// time. Default: [DefaultReservedHighPrioritySlots].
func WithReservedHighPrioritySlots(v int) Option {
	return func(o *options) {
		o.reservedHighPrioritySlots = v
	}
}

// WithStaleTaskTimeout sets the duration after which a task stuck in
// [TaskStatusRunning] is considered stale and reset to [TaskStatusActive] by
// the periodic recovery routine. Non-positive values are ignored.
// Default: [DefaultStaleTaskTimeout] (30 minutes).
func WithStaleTaskTimeout(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.staleTaskTimeout = v
	}
}

// WithTickInterval sets how often the scheduler's main loop evaluates pending
// tasks and dispatches due ones. Shorter intervals provide lower latency at the
// cost of higher CPU usage. Non-positive values are ignored.
// Default: [DefaultTickInterval] (1 second).
func WithTickInterval(v time.Duration) Option {
	return func(o *options) {
		if v <= 0 {
			return
		}
		o.tickInterval = v
	}
}

// defaultOptions returns the default values for options.
func defaultOptions() *options {
	return &options{
		cleanupInterval:           DefaultCleanupInterval,
		historyRetention:          DefaultHistoryRetention,
		logger:                    slog.New(slog.DiscardHandler),
		maxConcurrentTasks:        DefaultMaxConcurrentTasks,
		reservedHighPrioritySlots: DefaultReservedHighPrioritySlots,
		staleTaskTimeout:          DefaultStaleTaskTimeout,
		tickInterval:              DefaultTickInterval,
	}
}

// newOptions creates a new options with the given options.
func newOptions(opts ...Option) *options {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
